(function(){
  "use strict";
  const CLAVE="uniprep_notificaciones_v2";
  const ICONOS={logro:"🏆",curso:"📚",agenda:"⏰",simulacro:"📊",racha:"🔥",sistema:"✨"};
  function leer(){const datos=window.uniprepStorage?.leer(CLAVE,[]);return Array.isArray(datos)?datos:[]}
  function guardar(datos){window.uniprepStorage?.guardar(CLAVE,datos.slice(0,80))}
  function iniciales(){if(leer().length)return;guardar([{id:Date.now()-2,tipo:"sistema",titulo:"Bienvenido a UniPrep",cuerpo:"Tus recordatorios, resultados y nuevas actividades aparecerán aquí.",fecha:new Date().toISOString(),leida:false},{id:Date.now()-1,tipo:"curso",titulo:"Banco avanzado disponible",cuerpo:"Ya puedes practicar por curso y dificultad desde la sección Cursos.",fecha:new Date().toISOString(),leida:false}])}
  function relativo(fecha){const s=Math.max(0,Math.floor((Date.now()-new Date(fecha).getTime())/1000));if(s<60)return"Ahora";if(s<3600)return`Hace ${Math.floor(s/60)} min`;if(s<86400)return`Hace ${Math.floor(s/3600)} h`;return`Hace ${Math.floor(s/86400)} días`}
  function escapar(v){const d=document.createElement("div");d.textContent=String(v??"");return d.innerHTML}
  function registrar(datos,mostrarNativa=true){const item={id:Date.now()+Math.random(),tipo:datos.tipo||"sistema",titulo:datos.titulo||"UniPrep",cuerpo:datos.cuerpo||"",fecha:new Date().toISOString(),leida:false,accion:datos.accion||""},lista=leer();lista.unshift(item);guardar(lista);renderizar();if(mostrarNativa&&"Notification"in window&&Notification.permission==="granted")new Notification(item.titulo,{body:item.cuerpo,icon:"assets/uniprep-logo.png"});return item}
  function renderizar(){const pantalla=document.getElementById("notificaciones");if(!pantalla)return;const header=pantalla.querySelector(".page-header");let lista=document.getElementById("notifications-list");if(!lista){pantalla.querySelectorAll(":scope > .notif-item,:scope > div[style*='height:1px']").forEach(x=>x.remove());lista=document.createElement("div");lista.id="notifications-list";header.after(lista)}const datos=leer(),noLeidas=datos.filter(x=>!x.leida).length;const subt=header.querySelector(".page-subtitle");if(subt)subt.textContent=noLeidas?`${noLeidas} notificación${noLeidas===1?"":"es"} nueva${noLeidas===1?"":"s"}`:"Todo está al día";const boton=header.querySelector("button");if(boton){boton.textContent="Marcar todo como leído";boton.onclick=marcarTodas}if(!document.getElementById("enable-browser-notifications")){const b=document.createElement("button");b.id="enable-browser-notifications";b.className="btn btn-primary btn-sm";b.textContent="Activar avisos";b.onclick=solicitarPermiso;header.appendChild(b)}lista.innerHTML=datos.length?datos.map(n=>`<article class="notif-item ${n.leida?"":"unread"}" onclick="leerUna('${n.id}')"><div class="notif-icon-wrap">${ICONOS[n.tipo]||"🔔"}</div><div class="notif-content"><div class="notif-title">${escapar(n.titulo)}</div><div class="notif-body">${escapar(n.cuerpo)}</div><div class="notif-time">${relativo(n.fecha)}</div></div>${n.leida?"":'<div class="notif-unread-dot"></div>'}<button class="notification-delete" onclick="event.stopPropagation();eliminarNotificacion('${n.id}')" aria-label="Eliminar">×</button></article>`).join(""):'<div class="card notification-empty">🔕 No tienes notificaciones.</div>';actualizarBadge(noLeidas)}
  function actualizarBadge(n){document.querySelectorAll(".nav-item").forEach(i=>{if(!i.textContent.includes("Notificaciones"))return;let b=i.querySelector(".nav-badge");if(n&&!b){b=document.createElement("span");b.className="nav-badge";i.appendChild(b)}if(b){b.textContent=n;b.style.display=n?"":"none"}});const dot=document.querySelector(".topbar .notif-dot");if(dot)dot.style.display=n?"":"none"}
  function leerUna(id){const d=leer(),x=d.find(n=>String(n.id)===String(id));if(x)x.leida=true;guardar(d);renderizar()}
  function eliminar(id){guardar(leer().filter(n=>String(n.id)!==String(id)));renderizar()}
  function marcarTodas(){guardar(leer().map(n=>({...n,leida:true})));renderizar()}
  async function solicitarPermiso(){if(!("Notification"in window))return alert("Este navegador no admite notificaciones.");const p=await Notification.requestPermission();registrar({tipo:"sistema",titulo:p==="granted"?"Avisos activados":"Avisos no activados",cuerpo:p==="granted"?"UniPrep podrá mostrar recordatorios del calendario.":"Puedes activarlos después desde la configuración del navegador."},false)}
  function iniciar(){iniciales();renderizar();setInterval(()=>renderizar(),60000)}
  window.registrarNotificacion=registrar;window.renderizarNotificaciones=renderizar;window.leerUna=leerUna;window.eliminarNotificacion=eliminar;window.marcarTodasNotificaciones=marcarTodas;window.solicitarPermisoNotificaciones=solicitarPermiso;
  document.addEventListener("uniprep:user-ready",()=>{iniciales();renderizar()});
  document.addEventListener("uniprep:storage-scope-change",()=>{iniciales();renderizar()});
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",iniciar);else iniciar();
})();
