// Banco ampliado CEPRE-UNAMAD · Tema P · 100 preguntas
window.PREGUNTAS_CEPRE = [
// Razonamiento Matemático (10)
{area:"Matemática",tema:"Razonamiento Matemático",q:"Completa: 2, 5, 10, 17, 26, ...",o:["35","36","37","38"],r:2,e:"Las diferencias son 3,5,7,9 y 11; 26+11=37."},
{area:"Matemática",tema:"Razonamiento Matemático",q:"Si Ana es mayor que Luis y Luis es mayor que Pedro, ¿quién es el menor?",o:["Ana","Luis","Pedro","No se sabe"],r:2,e:"El orden es Ana > Luis > Pedro."},
{area:"Matemática",tema:"Razonamiento Matemático",q:"¿Cuántos triángulos hay al dividir un cuadrado con una diagonal?",o:["1","2","3","4"],r:1,e:"Una diagonal divide el cuadrado en dos triángulos."},
{area:"Matemática",tema:"Razonamiento Matemático",q:"Hace 5 años, Rosa tenía 12 años. ¿Qué edad tendrá dentro de 4 años?",o:["19","20","21","22"],r:2,e:"Ahora tiene 17 y dentro de 4 años tendrá 21."},
{area:"Matemática",tema:"Razonamiento Matemático",q:"Un auto viaja a 60 km/h durante 3 horas. ¿Qué distancia recorre?",o:["120 km","160 km","180 km","200 km"],r:2,e:"d=v·t=60·3=180 km."},
{area:"Matemática",tema:"Razonamiento Matemático",q:"En una reunión todos se saludan una vez. Si hay 5 personas, ¿cuántos saludos ocurren?",o:["5","8","10","20"],r:2,e:"C(5,2)=10 saludos."},
{area:"Matemática",tema:"Razonamiento Matemático",q:"Si hoy es martes, ¿qué día será dentro de 10 días?",o:["Jueves","Viernes","Sábado","Domingo"],r:1,e:"10 deja residuo 3 al dividir entre 7: martes+3=viernes."},
{area:"Matemática",tema:"Razonamiento Matemático",q:"Completa la analogía numérica: 3(4)5; 6(7)8; 9(?)11.",o:["9","10","11","12"],r:1,e:"El número central es el promedio de los extremos."},
{area:"Matemática",tema:"Razonamiento Matemático",q:"En una fila, Carla ocupa el séptimo lugar desde el inicio y el quinto desde el final. ¿Cuántas personas hay?",o:["10","11","12","13"],r:1,e:"7+5−1=11."},
{area:"Matemática",tema:"Razonamiento Matemático",q:"Dos engranajes de 20 y 40 dientes se conectan. Si el pequeño da 6 vueltas, ¿cuántas da el grande?",o:["2","3","6","12"],r:1,e:"Las vueltas son inversamente proporcionales: 20·6=40·x; x=3."},
// Aritmética (10)
{area:"Matemática",tema:"Aritmética",q:"¿Cuál es la unión de A={1,2,3} y B={3,4,5}?",o:["{3}","{1,2,4,5}","{1,2,3,4,5}","{1,2,3,3,4,5}"],r:2,e:"La unión reúne los elementos sin repetir."},
{area:"Matemática",tema:"Aritmética",q:"¿Cuál es el MCD de 24 y 36?",o:["6","8","12","18"],r:2,e:"El mayor divisor común es 12."},
{area:"Matemática",tema:"Aritmética",q:"¿Cuál es el MCM de 6 y 8?",o:["12","18","24","48"],r:2,e:"El menor múltiplo común es 24."},
{area:"Matemática",tema:"Aritmética",q:"Calcula 3/4 + 2/3.",o:["5/7","17/12","13/12","5/12"],r:1,e:"9/12+8/12=17/12."},
{area:"Matemática",tema:"Aritmética",q:"El 25% de 360 es:",o:["80","90","100","120"],r:1,e:"360·0,25=90."},
{area:"Matemática",tema:"Aritmética",q:"Si 5 cuadernos cuestan S/40, ¿cuánto cuestan 8?",o:["S/56","S/60","S/64","S/72"],r:2,e:"Cada cuaderno cuesta S/8; 8·8=S/64."},
{area:"Matemática",tema:"Aritmética",q:"Convierte 0,375 a fracción irreducible.",o:["3/5","3/8","5/8","37/100"],r:1,e:"0,375=375/1000=3/8."},
{area:"Matemática",tema:"Aritmética",q:"¿Cuántos divisores positivos tiene 12?",o:["4","5","6","8"],r:2,e:"Son 1,2,3,4,6 y 12: seis divisores."},
{area:"Matemática",tema:"Aritmética",q:"El promedio de 12, 15, 18 y 19 es:",o:["15","16","17","18"],r:1,e:"(12+15+18+19)/4=64/4=16."},
{area:"Matemática",tema:"Aritmética",q:"Una cantidad aumenta de 200 a 250. ¿Cuál fue el aumento porcentual?",o:["20%","25%","30%","50%"],r:1,e:"El aumento es 50 y 50/200=25%."},
// Álgebra (10)
{area:"Matemática",tema:"Álgebra",q:"Resuelve 3x+5=20.",o:["3","4","5","6"],r:2,e:"3x=15; x=5."},
{area:"Matemática",tema:"Álgebra",q:"Factoriza x²−16.",o:["(x−8)(x+2)","(x−4)(x+4)","(x−4)²","(x−16)(x+1)"],r:1,e:"Es diferencia de cuadrados."},
{area:"Matemática",tema:"Álgebra",q:"Simplifica (a³·a⁵)/a².",o:["a⁶","a⁷","a¹⁰","a¹⁵"],r:0,e:"Se suman y restan exponentes: 3+5−2=6."},
{area:"Matemática",tema:"Álgebra",q:"Si x+y=10 y x−y=4, ¿cuánto vale x?",o:["3","6","7","8"],r:2,e:"Sumando: 2x=14; x=7."},
{area:"Matemática",tema:"Álgebra",q:"Desarrolla (x+3)².",o:["x²+9","x²+3x+9","x²+6x+9","x²+6"],r:2,e:"(a+b)²=a²+2ab+b²."},
{area:"Matemática",tema:"Álgebra",q:"Las raíces de x²−5x+6=0 son:",o:["1 y 6","2 y 3","−2 y −3","3 y 5"],r:1,e:"(x−2)(x−3)=0."},
{area:"Matemática",tema:"Álgebra",q:"¿Cuál es el valor absoluto de −12?",o:["−12","0","12","24"],r:2,e:"El valor absoluto es la distancia al cero."},
{area:"Matemática",tema:"Álgebra",q:"Simplifica √50.",o:["2√5","5√2","10√5","25√2"],r:1,e:"√50=√(25·2)=5√2."},
{area:"Matemática",tema:"Álgebra",q:"Si P(x)=2x²−3x+1, calcula P(2).",o:["2","3","4","5"],r:1,e:"P(2)=8−6+1=3."},
{area:"Matemática",tema:"Álgebra",q:"Resuelve la desigualdad 2x−4>6.",o:["x>1","x>5","x<5","x≥5"],r:1,e:"2x>10; x>5."},
// Geometría (9)
{area:"Matemática",tema:"Geometría",q:"El suplemento de 65° es:",o:["25°","105°","115°","125°"],r:2,e:"Los ángulos suplementarios suman 180°."},
{area:"Matemática",tema:"Geometría",q:"La suma de los ángulos internos de un triángulo es:",o:["90°","180°","270°","360°"],r:1,e:"Todo triángulo suma 180°."},
{area:"Matemática",tema:"Geometría",q:"Un triángulo con lados 5,5,8 es:",o:["Equilátero","Isósceles","Escaleno","Rectángulo"],r:1,e:"Tiene dos lados iguales."},
{area:"Matemática",tema:"Geometría",q:"Área de un rectángulo de 9 m por 4 m:",o:["13 m²","26 m²","36 m²","45 m²"],r:2,e:"A=9·4=36 m²."},
{area:"Matemática",tema:"Geometría",q:"Área de un triángulo de base 10 cm y altura 6 cm:",o:["16 cm²","30 cm²","60 cm²","80 cm²"],r:1,e:"A=bh/2=30 cm²."},
{area:"Matemática",tema:"Geometría",q:"Longitud de una circunferencia de radio 3:",o:["3π","6π","9π","12π"],r:1,e:"L=2πr=6π."},
{area:"Matemática",tema:"Geometría",q:"Un polígono de ocho lados se llama:",o:["Hexágono","Heptágono","Octágono","Eneágono"],r:2,e:"Octágono tiene ocho lados."},
{area:"Matemática",tema:"Geometría",q:"Hipotenusa de un triángulo con catetos 9 y 12:",o:["13","14","15","16"],r:2,e:"√(81+144)=√225=15."},
{area:"Matemática",tema:"Geometría",q:"Volumen de un cubo de arista 4 cm:",o:["16 cm³","32 cm³","64 cm³","128 cm³"],r:2,e:"V=4³=64 cm³."},
// Trigonometría (9)
{area:"Matemática",tema:"Trigonometría",q:"180° equivalen a:",o:["π/2 rad","π rad","2π rad","3π rad"],r:1,e:"180°=π radianes."},
{area:"Matemática",tema:"Trigonometría",q:"En un triángulo rectángulo, sen θ es:",o:["Adyacente/hipotenusa","Opuesto/hipotenusa","Opuesto/adyacente","Hipotenusa/opuesto"],r:1,e:"sen θ=cateto opuesto/hipotenusa."},
{area:"Matemática",tema:"Trigonometría",q:"El valor de sen 30° es:",o:["0","1/2","√2/2","1"],r:1,e:"sen 30°=1/2."},
{area:"Matemática",tema:"Trigonometría",q:"El valor de cos 60° es:",o:["1/2","√2/2","√3/2","1"],r:0,e:"cos 60°=1/2."},
{area:"Matemática",tema:"Trigonometría",q:"El valor de tan 45° es:",o:["0","1/2","1","√3"],r:2,e:"tan 45°=1."},
{area:"Matemática",tema:"Trigonometría",q:"Completa: sen²x+cos²x=",o:["0","1","tan x","sec x"],r:1,e:"Es la identidad pitagórica fundamental."},
{area:"Matemática",tema:"Trigonometría",q:"Si cos θ=4/5 y θ es agudo, sen θ vale:",o:["1/5","2/5","3/5","5/4"],r:2,e:"Por la identidad pitagórica, sen θ=3/5."},
{area:"Matemática",tema:"Trigonometría",q:"La recíproca del coseno es:",o:["Cosecante","Cotangente","Secante","Tangente"],r:2,e:"sec x=1/cos x."},
{area:"Matemática",tema:"Trigonometría",q:"Un ángulo de 450° es coterminal con:",o:["45°","90°","180°","270°"],r:1,e:"450°−360°=90°."},
// Razonamiento Verbal (10)
{area:"Comunicación",tema:"Razonamiento Verbal",q:"Sinónimo de «efímero»:",o:["Eterno","Pasajero","Intenso","Antiguo"],r:1,e:"Efímero significa de corta duración."},
{area:"Comunicación",tema:"Razonamiento Verbal",q:"Antónimo de «hostil»:",o:["Amable","Agresivo","Áspero","Cruel"],r:0,e:"Amable se opone a hostil."},
{area:"Comunicación",tema:"Razonamiento Verbal",q:"MÉDICO : HOSPITAL :: DOCENTE :",o:["Libro","Escuela","Alumno","Pizarra"],r:1,e:"Son profesional y lugar de trabajo."},
{area:"Comunicación",tema:"Razonamiento Verbal",q:"Término excluido: violín, guitarra, piano, pincel.",o:["Violín","Guitarra","Piano","Pincel"],r:3,e:"Pincel no es instrumento musical."},
{area:"Comunicación",tema:"Razonamiento Verbal",q:"Complete: El científico formuló una ___ y luego realizó un experimento para comprobarla.",o:["duda","hipótesis","noticia","leyenda"],r:1,e:"Una hipótesis se somete a comprobación."},
{area:"Comunicación",tema:"Razonamiento Verbal",q:"Orden lógico: 1. Germina la semilla. 2. Se riega la tierra. 3. Se coloca la semilla. 4. Crece la planta.",o:["2-3-1-4","3-2-4-1","1-2-3-4","3-1-2-4"],r:0,e:"Primero se prepara/riega, se siembra, germina y crece."},
{area:"Comunicación",tema:"Razonamiento Verbal",q:"Sinónimo contextual de «mitigar»:",o:["Aumentar","Disminuir","Ocultar","Prohibir"],r:1,e:"Mitigar es reducir o aliviar."},
{area:"Comunicación",tema:"Razonamiento Verbal",q:"CAPÍTULO : LIBRO :: ESCENA :",o:["Actor","Teatro","Obra","Público"],r:2,e:"El capítulo integra un libro y la escena una obra."},
{area:"Comunicación",tema:"Razonamiento Verbal",q:"Antónimo de «escasez»:",o:["Pobreza","Abundancia","Carencia","Limitación"],r:1,e:"Abundancia se opone a escasez."},
{area:"Comunicación",tema:"Razonamiento Verbal",q:"Término excluido: honestidad, justicia, solidaridad, velocidad.",o:["Honestidad","Justicia","Solidaridad","Velocidad"],r:3,e:"Las tres primeras son valores."},
// Comprensión Lectora (7)
{area:"Comunicación",tema:"Comprensión Lectora",q:"Texto: «El agua es indispensable para la vida; por ello debemos evitar su desperdicio». Idea principal:",o:["El agua es barata","Debemos cuidar el agua porque es vital","La vida ocurre en el agua","El desperdicio es inevitable"],r:1,e:"Resume las dos ideas del texto."},
{area:"Comunicación",tema:"Comprensión Lectora",q:"Texto: «La lectura amplía el vocabulario y fortalece el pensamiento crítico». ¿Qué beneficio NO se menciona?",o:["Más vocabulario","Pensamiento crítico","Mejor condición física","Comprensión"],r:2,e:"El texto no habla de condición física."},
{area:"Comunicación",tema:"Comprensión Lectora",q:"Texto: «Aunque el camino era difícil, los viajeros llegaron». Se infiere que:",o:["Abandonaron","Superaron la dificultad","El camino fue corto","No hubo obstáculos"],r:1,e:"Llegaron pese a la dificultad."},
{area:"Comunicación",tema:"Comprensión Lectora",q:"Texto: «Los bosques capturan carbono y albergan biodiversidad». El tema es:",o:["La agricultura","La importancia de los bosques","El clima urbano","Los animales domésticos"],r:1,e:"Ambas ideas describen funciones de los bosques."},
{area:"Comunicación",tema:"Comprensión Lectora",q:"Texto: «Marta estudió toda la semana. El día del examen respondió con seguridad». La seguridad fue consecuencia de:",o:["La suerte","El estudio","La facilidad","La ayuda"],r:1,e:"El texto relaciona su preparación con su seguridad."},
{area:"Comunicación",tema:"Comprensión Lectora",q:"En «La ciudad despertó cubierta por un manto blanco», manto blanco alude a:",o:["Nieve","Humo","Nubes","Pintura"],r:0,e:"Es una expresión metafórica referida a la nieve."},
{area:"Comunicación",tema:"Comprensión Lectora",q:"Texto: «Reciclar reduce residuos, pero también exige separar correctamente los materiales». ¿Qué conector podría reemplazar «pero también»?",o:["Por eso","Además","Sin embargo","Porque"],r:1,e:"Añade otra idea, por lo que corresponde «además»."},
// Lenguaje (4)
{area:"Comunicación",tema:"Lenguaje",q:"En «María compró frutas», el sujeto es:",o:["Compró","Frutas","María","Compró frutas"],r:2,e:"María realiza la acción."},
{area:"Comunicación",tema:"Lenguaje",q:"¿Cuál palabra es esdrújula?",o:["Reloj","Canción","Árbol","Química"],r:3,e:"Quí-mi-ca se acentúa en la antepenúltima sílaba."},
{area:"Comunicación",tema:"Lenguaje",q:"La comunicación mediante gestos utiliza un código:",o:["Verbal","No verbal","Escrito","Lingüístico"],r:1,e:"Los gestos son signos no verbales."},
{area:"Comunicación",tema:"Lenguaje",q:"¿Cuál oración está correctamente puntuada?",o:["Pedro ven aquí.","Pedro, ven aquí.","Pedro ven, aquí.","Pedro; ven aquí,"],r:1,e:"El vocativo Pedro se separa con coma."},
// Literatura (4)
{area:"Comunicación",tema:"Literatura",q:"El género que representa acciones mediante diálogos es:",o:["Lírico","Épico","Dramático","Ensayístico"],r:2,e:"El género dramático está destinado a la representación."},
{area:"Comunicación",tema:"Literatura",q:"¿Quién escribió «Paco Yunque»?",o:["César Vallejo","Ciro Alegría","Ricardo Palma","José María Arguedas"],r:0,e:"Es un cuento de César Vallejo."},
{area:"Comunicación",tema:"Literatura",q:"Una comparación explícita usa generalmente la palabra:",o:["Como","Pero","Porque","Aunque"],r:0,e:"El símil suele emplear «como»."},
{area:"Comunicación",tema:"Literatura",q:"«Los ríos profundos» fue escrita por:",o:["Mario Vargas Llosa","José María Arguedas","Abraham Valdelomar","Julio Ramón Ribeyro"],r:1,e:"Es una novela de José María Arguedas."},
// Geografía (3)
{area:"Sociales",tema:"Geografía",q:"La ciencia que representa la superficie terrestre mediante mapas es:",o:["Geología","Cartografía","Demografía","Economía"],r:1,e:"La cartografía elabora y estudia mapas."},
{area:"Sociales",tema:"Geografía",q:"La capital de Madre de Dios es:",o:["Iñapari","Mazuko","Puerto Maldonado","Tambopata"],r:2,e:"Puerto Maldonado es la capital departamental."},
{area:"Sociales",tema:"Geografía",q:"La línea imaginaria que divide la Tierra en hemisferios norte y sur es:",o:["Greenwich","Ecuador","Trópico de Capricornio","Círculo Polar"],r:1,e:"La línea ecuatorial divide ambos hemisferios."},
// Economía (2)
{area:"Sociales",tema:"Economía",q:"El problema económico fundamental surge porque:",o:["Los recursos son ilimitados","Las necesidades son limitadas","Los recursos son escasos y las necesidades ilimitadas","No existe producción"],r:2,e:"La escasez obliga a elegir cómo usar los recursos."},
{area:"Sociales",tema:"Economía",q:"El PBI mide:",o:["Solo exportaciones","Producción final de un país","Dinero de los bancos","Número de habitantes"],r:1,e:"Mide el valor de bienes y servicios finales producidos."},
// Filosofía (2)
{area:"Sociales",tema:"Filosofía",q:"La filosofía surgió históricamente como paso del mito al:",o:["Rito","Logos","Arte","Dogma"],r:1,e:"Logos significa explicación racional."},
{area:"Sociales",tema:"Filosofía",q:"La rama que estudia el conocimiento es:",o:["Ética","Estética","Gnoseología","Axiología"],r:2,e:"La gnoseología estudia el conocimiento."},
// Química (5)
{area:"Ciencias",tema:"Química",q:"La unidad básica de un elemento químico es:",o:["Molécula","Átomo","Célula","Ion"],r:1,e:"El átomo conserva las propiedades del elemento."},
{area:"Ciencias",tema:"Química",q:"El número atómico indica la cantidad de:",o:["Neutrones","Protones","Nucleones","Orbitales"],r:1,e:"Z es el número de protones."},
{area:"Ciencias",tema:"Química",q:"¿Cuál es una mezcla homogénea?",o:["Agua y aceite","Arena y agua","Aire","Ensalada"],r:2,e:"El aire presenta composición uniforme."},
{area:"Ciencias",tema:"Química",q:"El cloro (Z=17) pertenece a los:",o:["Alcalinos","Halógenos","Gases nobles","Lantánidos"],r:1,e:"El cloro pertenece al grupo 17: halógenos."},
{area:"Ciencias",tema:"Química",q:"La fórmula del dióxido de carbono es:",o:["CO","CO₂","C₂O","O₂C₂"],r:1,e:"Contiene un carbono y dos oxígenos."},
// Biología (2)
{area:"Ciencias",tema:"Biología",q:"La unidad estructural y funcional de los seres vivos es:",o:["Átomo","Tejido","Célula","Órgano"],r:2,e:"La célula es la unidad básica de la vida."},
{area:"Ciencias",tema:"Biología",q:"El organelo encargado principalmente de producir ATP es:",o:["Núcleo","Ribosoma","Mitocondria","Lisosoma"],r:2,e:"La respiración celular ocurre principalmente en la mitocondria."},
// Medio Ambiente (4)
{area:"Ciencias",tema:"Medio Ambiente",q:"Un ecosistema está formado por:",o:["Solo animales","Solo plantas","Seres vivos y factores físicos","Únicamente agua y suelo"],r:2,e:"Integra componentes bióticos y abióticos."},
{area:"Ciencias",tema:"Medio Ambiente",q:"Los organismos que producen su propio alimento son:",o:["Consumidores","Descomponedores","Productores","Parásitos"],r:2,e:"Los autótrofos son productores."},
{area:"Ciencias",tema:"Medio Ambiente",q:"¿Cuál es un recurso renovable?",o:["Petróleo","Carbón","Energía solar","Gas natural"],r:2,e:"La energía solar se repone naturalmente."},
{area:"Ciencias",tema:"Medio Ambiente",q:"La pérdida extensa de bosques se denomina:",o:["Eutrofización","Deforestación","Sedimentación","Desertización marina"],r:1,e:"Deforestación es la eliminación de cobertura boscosa."},
// Física (5)
{area:"Ciencias",tema:"Física",q:"La unidad de longitud en el SI es:",o:["Segundo","Metro","Kilogramo","Newton"],r:1,e:"El metro es la unidad básica de longitud."},
{area:"Ciencias",tema:"Física",q:"Un móvil recorre 150 m en 30 s. Su rapidez es:",o:["3 m/s","5 m/s","15 m/s","45 m/s"],r:1,e:"v=150/30=5 m/s."},
{area:"Ciencias",tema:"Física",q:"Una magnitud vectorial es:",o:["Masa","Tiempo","Temperatura","Fuerza"],r:3,e:"La fuerza tiene módulo, dirección y sentido."},
{area:"Ciencias",tema:"Física",q:"Si un cuerpo parte del reposo con aceleración 2 m/s² durante 4 s, su velocidad final es:",o:["2 m/s","6 m/s","8 m/s","16 m/s"],r:2,e:"v=v₀+at=0+2·4=8 m/s."},
{area:"Ciencias",tema:"Física",q:"La primera ley de Newton también se llama ley de:",o:["Gravitación","Inercia","Acción y reacción","Conservación de carga"],r:1,e:"Describe la tendencia a conservar el estado de movimiento."},
// Educación Cívica (4)
{area:"Cívica",tema:"Educación Cívica",q:"La norma suprema del Estado peruano es:",o:["Código Civil","Constitución Política","Decreto Supremo","Ordenanza"],r:1,e:"La Constitución posee la máxima jerarquía."},
{area:"Cívica",tema:"Educación Cívica",q:"En el Perú, la ciudadanía se ejerce desde los:",o:["16 años","17 años","18 años","21 años"],r:2,e:"Se adquiere al cumplir 18 años, salvo suspensión legal."},
{area:"Cívica",tema:"Educación Cívica",q:"¿Cuál es un derecho fundamental?",o:["Discriminar","Identidad","Censurar","Evitar impuestos"],r:1,e:"Toda persona tiene derecho a su identidad."},
{area:"Cívica",tema:"Educación Cívica",q:"El poder del Estado encargado de administrar justicia es el:",o:["Ejecutivo","Legislativo","Judicial","Electoral"],r:2,e:"El Poder Judicial administra justicia."}
];
