(function () {
  "use strict";

  const KEYS = {
    view:"uniprep_tutor_studio_view_v1",
    packs:"uniprep_tutor_study_packs_v1",
    active:"uniprep_tutor_active_pack_v1"
  };
  const VIEWS = new Set(["preguntar", "preparacion", "materiales", "historial"]);
  const ALLOWED_MIME = new Set([
    "application/pdf", "application/msword",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "application/vnd.ms-powerpoint",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    "application/vnd.ms-excel",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "text/plain", "text/markdown", "text/csv", "text/tab-separated-values", "application/json",
    "image/png", "image/jpeg", "image/webp"
  ]);
  const TEXT_MIME = new Set(["text/plain", "text/markdown", "text/csv", "text/tab-separated-values", "application/json"]);
  const MAX_FILE = 2.4 * 1024 * 1024;

  function read(key, fallback) { return window.uniprepStorage?.leer(key, fallback) ?? fallback; }
  function write(key, value) { window.uniprepStorage?.guardar(key, value); }
  function readText(key, fallback) { return window.uniprepStorage?.leerTexto(key, fallback) || fallback; }
  function writeText(key, value) { window.uniprepStorage?.guardarTexto(key, value); }
  function esc(value) { const node=document.createElement("div"); node.textContent=String(value ?? ""); return node.innerHTML; }
  function safeText(value, max=1000) { return String(value ?? "").trim().slice(0,max); }
  function dateAfter(days) { const date=new Date(); date.setHours(12,0,0,0); date.setDate(date.getDate()+days); return date.toISOString().slice(0,10); }
  function daysUntil(value) { const target=new Date(`${value || dateAfter(0)}T12:00:00`); const today=new Date(); today.setHours(12,0,0,0); return Math.max(0,Math.ceil((target-today)/86400000)); }
  function uid() { return `pack_${Date.now()}_${Math.random().toString(36).slice(2,8)}`; }

  function freshSetup() {
    return {courseId:readText("uniprep_tutor_course_v1","rm"), date:dateAfter(14), target:80, institution:"", level:"Preuniversitario", text:"", file:null};
  }

  const state = {
    view:readText(KEYS.view,"preparacion"), step:0, setup:freshSetup(), packs:read(KEYS.packs,[]),
    activeId:readText(KEYS.active,""), module:"home", activity:null, busy:false, error:"", user:null,
    loadingText:"Leyendo tu material…"
  };
  if (!VIEWS.has(state.view)) state.view="preparacion";
  if (!Array.isArray(state.packs)) state.packs=[];

  function courses() {
    return Object.values(window.CURSOS_PREUNI || {}).filter(course=>window.cursoPermitidoAdmision?.(course.id)!==false);
  }
  function courseById(id) {
    return window.CURSOS_PREUNI?.[id] || courses().find(course=>course.id===id) || courses()[0] || {id:"rm",nombre:"Razonamiento Matemático",icono:"🧠",descripcion:"Preparación preuniversitaria",temas:[]};
  }
  function activePack() { return state.packs.find(pack=>pack.id===state.activeId) || null; }
  function savePacks(sync=true) { state.packs=state.packs.filter(pack=>pack?.id&&pack?.title).slice(0,12); write(KEYS.packs,state.packs); if(sync)state.packs.forEach(pack=>window.UniPrepCloud?.saveStudyPack?.(pack)); }
  function rerender() { window.renderizarTutorAcademico?.(); }

  function renderNav() {
    const messages=read("uniprep_tutor_history_v1",[]);
    const button=(id,icon,label,count)=>`<button type="button" class="${state.view===id?"active":""}" onclick="UniprepTutorStudio.setView('${id}')"><i>${icon}</i><span>${label}</span>${count?`<b>${count}</b>`:""}</button>`;
    return `<nav class="tutor-studio-nav" aria-label="Herramientas de Uni, Tutor IA">${button("preguntar","✦","Preguntar",0)}${button("preparacion","🎯","Preparación para examen",0)}${button("materiales","📚","Mis materiales",state.packs.length)}${button("historial","🕘","Conversaciones",Array.isArray(messages)?messages.length:0)}<span class="tutor-service-pill"><i></i> IA + guía local</span></nav>`;
  }

  async function renderIfNeeded(root,user) {
    state.user=user || null;
    state.packs=read(KEYS.packs,[]);
    state.activeId=readText(KEYS.active,state.activeId);
    if (!Array.isArray(state.packs)) state.packs=[];
    if (state.view==="preguntar") return false;
    if (!state.setup.institution) state.setup.institution=safeText(user?.universidad || user?.university || "",100);
    if (!courses().some(course=>course.id===state.setup.courseId)) state.setup.courseId=courses()[0]?.id || "rm";
    if (state.activeId&&!activePack()) { state.activeId=""; writeText(KEYS.active,""); }
    const first=safeText(user?.nombre,80).split(/\s+/)[0];
    root.innerHTML=`<section class="tutor-studio-shell"><header class="tutor-head"><div class="tutor-head-copy"><small>UNIPREP INTELIGENCIA EDUCATIVA</small><h1>${first?`Hola, ${esc(first)}. `:""}Estudia con una ruta creada para ti.</h1><p>Convierte tus apuntes en resúmenes, tarjetas, audiolecciones, ejercicios y simulacros. Todo dentro de UniPrep.</p></div><div class="tutor-head-status"><span class="tutor-orb">✦</span><b>Uni, tu Tutor IA</b><em id="tutor-service-status">Comprobando servicio…</em></div></header>${renderNav()}<main class="tutor-studio-view">${renderContent()}</main></section>`;
    checkService();
    return true;
  }

  function setView(view, silent=false) {
    if (!VIEWS.has(view)) return;
    state.view=view; writeText(KEYS.view,view); state.step=0; state.error=""; state.module="home"; state.activity=null;
    if (!silent) rerender();
  }

  function renderContent() {
    if (state.view==="materiales") return renderLibrary();
    if (state.view==="historial") return renderHistory();
    if (state.busy) return renderLoading();
    if (state.step) return renderWizard();
    if (activePack()) return renderWorkspace();
    return renderHome();
  }

  function renderHome() {
    const recent=state.packs.slice(0,3);
    return `<section class="tutor-prep-home"><div class="tutor-prep-intro"><div><span class="tutor-eyebrow">PREPARACIÓN PERSONALIZADA</span><h2>Todo lo necesario para tu próximo examen.</h2><p>Elige la materia, la fecha y tu meta. Después sube un PDF, Word, presentación, imagen o pega tus apuntes. Uni generará una ruta completa y personal.</p></div><button type="button" class="tutor-primary-cta" onclick="iniciarPreparacionIA()"><span>＋</span> Crear preparación con IA</button></div><div class="tutor-feature-strip"><article><i>📄</i><div><b>Resumen inteligente</b><small>Ideas clave bien organizadas</small></div></article><article><i>🧠</i><div><b>Tarjetas de memoria</b><small>Repaso activo y rápido</small></div></article><article><i>✅</i><div><b>Práctica inmediata</b><small>Corrección y explicación</small></div></article><article><i>🎧</i><div><b>Audiolección</b><small>Escucha el contenido generado</small></div></article></div><div class="tutor-section-title"><div><span>ESPACIOS DE ESTUDIO</span><h3>${recent.length?"Continúa donde lo dejaste":"Crea tu primer espacio"}</h3></div>${state.packs.length>3?'<button onclick="UniprepTutorStudio.setView(\'materiales\')">Ver todos →</button>':""}</div>${recent.length?`<div class="tutor-pack-grid">${recent.map(renderPackCard).join("")}</div>`:renderEmpty()}<div class="tutor-cost-note"><span>💸</span><div><b>Diseñado para cuidar tus créditos</b><p>Una sola consulta genera el paquete completo. Después puedes estudiar, escuchar y practicar sin gastar por cada tarjeta.</p></div></div></section>`;
  }

  function renderEmpty() { return `<button class="tutor-empty-pack" type="button" onclick="iniciarPreparacionIA()"><span>✦</span><b>Preparar un examen</b><p>Sube tus apuntes y conviértelos en una experiencia interactiva.</p><em>Empezar ahora →</em></button>`; }
  function renderPackCard(pack) { return `<article class="tutor-pack-card"><div class="tutor-pack-card-top"><span>${pack.courseIcon||"📘"}</span><em class="${pack.origin==="ai"?"ai":"local"}">${pack.origin==="ai"?"✦ IA":"Guía local"}</em></div><h4>${esc(pack.title)}</h4><p>${esc(pack.materialName||pack.courseName)}</p><div class="tutor-pack-stats"><span><b>${daysUntil(pack.examDate)}</b> días</span><span><b>${pack.target}%</b> meta</span><span><b>${pack.quiz?.length||0}</b> preguntas</span></div><button type="button" onclick="abrirPaqueteIA('${pack.id}')">Continuar estudiando →</button></article>`; }

  function startPreparation() {
    state.setup=freshSetup(); state.setup.institution=safeText(state.user?.universidad || state.user?.university || "",100);
    state.step=1; state.error=""; state.activeId=""; state.module="home"; writeText(KEYS.active,"");
    state.view="preparacion"; writeText(KEYS.view,state.view); rerender();
  }

  function renderWizard() {
    const titles=["Elige una materia","¿Cuándo tienes el examen?","¿Qué calificación quieres obtener?","Personaliza tu preparación","Sube tu material de estudio"];
    const subtitles=["La ruta se adaptará al curso y al temario de UniPrep.","Usaremos la fecha para organizar el ritmo de estudio.","Tu meta se mostrará durante toda la preparación.","Ajustaremos el nivel y el tipo de ejercicios.","El archivo se analiza temporalmente; solo guardamos el paquete generado."];
    return `<section class="tutor-wizard"><div class="tutor-wizard-top"><button onclick="prevStep()">←</button><div class="tutor-wizard-progress"><span style="width:${state.step*20}%"></span></div><b>${state.step}/5</b><button onclick="cancelPreparation()">×</button></div><header><span>PASO ${state.step}</span><h2>${titles[state.step-1]}</h2><p>${subtitles[state.step-1]}</p></header><div class="tutor-wizard-body">${renderStep()}</div><footer>${state.step>1?'<button class="tutor-secondary-button" onclick="prevStep()">Atrás</button>':'<span></span>'}<button class="tutor-primary-button" onclick="nextStep()">${state.step===5?"Generar mi espacio ✦":"Continuar →"}</button></footer></section>`;
  }

  function renderStep() {
    if (state.step===1) return `<div class="tutor-subject-grid">${courses().map(course=>`<button class="${state.setup.courseId===course.id?"active":""}" onclick="selectSubject('${esc(course.id)}')"><i>${course.icono||"📘"}</i><span>${esc(course.nombre)}</span><small>${course.temas?.length||0} temas</small></button>`).join("")}</div>`;
    if (state.step===2) return `<div class="tutor-date-panel"><div class="tutor-calendar-icon">📅</div><label>Fecha del examen<input id="tutor-exam-date" type="date" min="${dateAfter(0)}" value="${esc(state.setup.date)}" onchange="setExamDate(this.value)"></label><div class="tutor-date-count"><b>${daysUntil(state.setup.date)}</b><span>días restantes</span></div></div><div class="tutor-date-chips"><button onclick="quickDate(3)">En 3 días</button><button onclick="quickDate(7)">En 1 semana</button><button onclick="quickDate(14)">En 2 semanas</button><button onclick="quickDate(30)">En 1 mes</button></div>`;
    if (state.step===3) return `<div class="tutor-goal-panel"><div class="tutor-goal-ring" id="tutor-goal-ring" style="--goal:${state.setup.target*3.6}deg"><div><b id="tutor-goal-value">${state.setup.target}%</b><span>meta</span></div></div><label class="tutor-goal-slider"><span>Meta de calificación</span><input id="tutor-goal-input" type="range" min="10" max="100" value="${state.setup.target}" oninput="updateGoal(this.value)"><div><small>10%</small><small>100%</small></div></label></div><div class="tutor-goal-message">${state.setup.target>=90?"🏆 Prepararemos práctica de máxima precisión.":state.setup.target>=70?"🚀 Reforzaremos conceptos y errores frecuentes.":"🌱 Empezaremos por las bases y subiremos gradualmente."}</div>`;
    if (state.step===4) return `<div class="tutor-profile-fields"><label>Institución o universidad objetivo<input id="tutor-prep-institution" maxlength="100" value="${esc(state.setup.institution)}" placeholder="Ejemplo: UNAMAD, UNI o mi colegio"></label><fieldset><legend>Nivel de preparación</legend>${["Secundaria","Preuniversitario","Universidad"].map(level=>`<button class="${state.setup.level===level?"active":""}" onclick="selectLevel('${level}')"><i>${level==="Secundaria"?"🎒":level==="Preuniversitario"?"🎯":"🎓"}</i><span>${level}</span></button>`).join("")}</fieldset><div class="tutor-data-note"><span>🔒</span><p>La IA recibe contexto académico, no DNI, teléfono ni dirección.</p></div></div>`;
    return renderUploadStep();
  }

  function renderUploadStep() {
    const file=state.setup.file;
    return `<div class="tutor-material-step"><input id="tutor-material-file" type="file" hidden accept=".pdf,.doc,.docx,.ppt,.pptx,.xls,.xlsx,.txt,.md,.csv,.tsv,.json,.png,.jpg,.jpeg,.webp" onchange="processTutorFile(this.files[0])"><div class="tutor-upload-zone ${file?"has-file":""}" role="button" tabindex="0" onclick="document.getElementById('tutor-material-file').click()" onkeydown="if(event.key==='Enter'||event.key===' '){event.preventDefault();this.click()}" ondragover="event.preventDefault();this.classList.add('dragging')" ondragleave="this.classList.remove('dragging')" ondrop="dropTutorFile(event)">${file?`<span class="tutor-file-icon">${fileIcon(file.mime)}</span><div><b>${esc(file.name)}</b><small>${formatBytes(file.size)} · listo para analizar</small></div><button onclick="event.stopPropagation();removeTutorFile()">×</button>`:'<span class="tutor-upload-icon">⇧</span><b>Sube tus apuntes o material</b><p>Arrastra el archivo aquí o presiónalo para elegirlo</p><small>PDF, Word, PowerPoint, Excel, texto o imagen · máximo 2.4 MB</small>'}</div><div class="tutor-material-divider"><span>o pega el contenido</span></div><label class="tutor-paste-field"><span>Texto, fórmulas o instrucciones del profesor</span><textarea id="tutor-material-text" maxlength="60000" placeholder="Pega aquí tus apuntes o temario…">${esc(state.setup.text)}</textarea><small>El contenido se trata como material académico, no como instrucciones del sistema.</small></label><button class="tutor-built-in-button" onclick="useBuiltInSyllabus()">📚 Usar el temario integrado de ${esc(courseById(state.setup.courseId).nombre)}</button>${state.error?`<div class="tutor-form-error">⚠ ${esc(state.error)}</div>`:""}</div>`;
  }

  function selectSubject(id) { if (!courses().some(course=>course.id===id)) return; state.setup.courseId=id; writeText("uniprep_tutor_course_v1",id); rerender(); }
  function setExamDate(value) { if (value) state.setup.date=value; rerender(); }
  function quickDate(days) { state.setup.date=dateAfter(days); rerender(); }
  function updateGoal(value) { state.setup.target=Math.min(100,Math.max(10,Number(value)||80)); document.getElementById("tutor-goal-value")?.replaceChildren(`${state.setup.target}%`); document.getElementById("tutor-goal-ring")?.style.setProperty("--goal",`${state.setup.target*3.6}deg`); }
  function selectLevel(level) { if (!["Secundaria","Preuniversitario","Universidad"].includes(level)) return; state.setup.institution=document.getElementById("tutor-prep-institution")?.value.trim()||state.setup.institution; state.setup.level=level; rerender(); }
  function captureText() { const area=document.getElementById("tutor-material-text"); if (area) state.setup.text=area.value.trim().slice(0,60000); }
  function nextStep() { state.error=""; if(state.step===2) state.setup.date=document.getElementById("tutor-exam-date")?.value||state.setup.date; if(state.step===3) state.setup.target=Number(document.getElementById("tutor-goal-input")?.value)||state.setup.target; if(state.step===4) state.setup.institution=document.getElementById("tutor-prep-institution")?.value.trim()||""; if(state.step===5) return generateStudyPack(); state.step++; rerender(); }
  function prevStep() { if(state.step<=1) return cancelPreparation(); if(state.step===5) captureText(); state.step--; state.error=""; rerender(); }
  function cancelPreparation() { state.step=0; state.setup.file=null; state.error=""; rerender(); }

  function mimeFromName(name) {
    const ext=String(name||"").toLowerCase().split(".").pop();
    return ({pdf:"application/pdf",doc:"application/msword",docx:"application/vnd.openxmlformats-officedocument.wordprocessingml.document",ppt:"application/vnd.ms-powerpoint",pptx:"application/vnd.openxmlformats-officedocument.presentationml.presentation",xls:"application/vnd.ms-excel",xlsx:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",txt:"text/plain",md:"text/markdown",csv:"text/csv",tsv:"text/tab-separated-values",json:"application/json",png:"image/png",jpg:"image/jpeg",jpeg:"image/jpeg",webp:"image/webp"})[ext]||"application/octet-stream";
  }
  function readDataURL(file) { return new Promise((resolve,reject)=>{ const reader=new FileReader(); reader.onload=()=>resolve(String(reader.result||"")); reader.onerror=reject; reader.readAsDataURL(file); }); }
  async function processFile(file) {
    if(!file) return; captureText(); const reported=String(file.type||"").toLowerCase(); const mime=ALLOWED_MIME.has(reported)?reported:mimeFromName(file.name);
    if(!ALLOWED_MIME.has(mime)){state.error="Formato no permitido. Usa PDF, Word, PowerPoint, Excel, texto o imagen.";return rerender();}
    if(file.size>MAX_FILE){state.error="El archivo supera 2.4 MB. Comprímelo o pega solo las páginas importantes.";return rerender();}
    state.error="";
    try { if(TEXT_MIME.has(mime)){state.setup.text=[state.setup.text,await file.text()].filter(Boolean).join("\n\n").slice(0,60000);state.setup.file={name:file.name,mime,size:file.size,data:""};} else state.setup.file={name:file.name,mime,size:file.size,data:await readDataURL(file)}; }
    catch(_){state.error="No se pudo leer el archivo. Prueba con otro o pega el texto.";}
    rerender();
  }
  function dropFile(event){event.preventDefault();event.currentTarget?.classList.remove("dragging");processFile(event.dataTransfer?.files?.[0]);}
  function removeFile(){state.setup.file=null;state.error="";rerender();}
  function fileIcon(mime){return mime==="application/pdf"?"📕":mime?.startsWith("image/")?"🖼️":mime?.includes("presentation")?"📊":mime?.includes("sheet")||mime?.includes("excel")?"📈":"📄";}
  function formatBytes(bytes){return bytes<1024?`${bytes} B`:bytes<1048576?`${Math.round(bytes/1024)} KB`:`${(bytes/1048576).toFixed(1)} MB`;}
  function useBuiltIn(){const course=courseById(state.setup.courseId);state.setup.text=[`Curso: ${course.nombre}.`,course.descripcion||"","Temas:",...(course.temas||[]).slice(0,30).map((topic,index)=>`${index+1}. ${topic.titulo}${topic.descripcion?`: ${topic.descripcion}`:""}`)].filter(Boolean).join("\n").slice(0,60000);state.error="";rerender();}

  async function getToken(){const session=await window.supabaseClient?.auth?.getSession?.();return session?.data?.session?.access_token||"";}
  async function requestPack(){const token=await getToken();if(!token)throw new Error("SIN_SESION");const course=courseById(state.setup.courseId);const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),90000);try{const response=await fetch("/api/tutor",{method:"POST",headers:{"Content-Type":"application/json","Authorization":`Bearer ${token}`},body:JSON.stringify({accion:"study_pack",curso:course.nombre,tema:course.temas?.[0]?.titulo||"Temario general",examen:{fecha:state.setup.date,meta:state.setup.target,institucion:state.setup.institution,nivel:state.setup.level},material:{name:state.setup.file?.name||"apuntes-pegados.txt",mime:state.setup.file?.mime||"text/plain",data:state.setup.file?.data||"",text:state.setup.text.slice(0,60000)}}),signal:controller.signal});const data=await response.json().catch(()=>({}));if(!response.ok||!data.studyPack)throw new Error(data.code||"IA_NO_CONFIGURADA");return{...data.studyPack,origin:"ai",__usage:data.usage||null,__model:data.model||"gpt-5.6-luna"};}finally{clearTimeout(timeout);}}

  async function generateStudyPack(){captureText();if(!state.setup.file&&state.setup.text.length<40){state.error="Sube un archivo, pega tus apuntes o usa el temario integrado.";return rerender();}state.busy=true;state.loadingText="Leyendo tu material…";state.error="";rerender();const stages=["Leyendo tu material…","Detectando ideas importantes…","Creando tarjetas de memoria…","Preparando ejercicios con explicación…","Organizando tu ruta de estudio…"];let index=0;const timer=setInterval(()=>{index=Math.min(stages.length-1,index+1);state.loadingText=stages[index];const label=document.getElementById("tutor-loading-message");if(label)label.textContent=state.loadingText;const bar=document.getElementById("tutor-loading-progress");if(bar)bar.style.width=`${Math.min(92,18+index*18)}%`;},2600);try{let pack;try{pack=await requestPack();if(pack.__usage)await window.UniPrepCloud?.trackUsage?.(pack.__usage,pack.__model,"study_pack");}catch(error){pack=localPack(error?.message||"IA_NO_DISPONIBLE");}const normalized=normalizePack(pack);state.packs=[normalized,...state.packs].slice(0,12);savePacks();state.activeId=normalized.id;writeText(KEYS.active,normalized.id);state.step=0;state.setup.file=null;state.module="home";state.activity=null;}finally{clearInterval(timer);state.busy=false;rerender();}}
  function renderLoading(){return `<section class="tutor-ai-loading"><div class="tutor-loading-orbit"><span>✦</span><i></i><i></i><i></i></div><span class="tutor-eyebrow">UNI ESTÁ TRABAJANDO</span><h2 id="tutor-loading-message">${esc(state.loadingText)}</h2><p>Esto puede tardar unos segundos. No cierres la página.</p><div class="tutor-loading-track"><span id="tutor-loading-progress" style="width:18%"></span></div><div class="tutor-loading-items"><span>✓ Contexto del examen</span><span>✓ Nivel y meta</span><span>◌ Material académico</span></div></section>`;}

  function localPack(reason){const course=courseById(state.setup.courseId);const topics=(course.temas||[]).slice(0,8);const concepts=topics.slice(0,6).map(topic=>({title:topic.titulo,explanation:topic.descripcion||`Tema esencial de ${course.nombre}. Repasa su definición, propiedades y procedimiento.`,example:(topic.puntos||[]).slice(0,2).join(" · ")||"Aplica la idea en el banco de UniPrep."}));const other=courses().filter(item=>item.id!==course.id).flatMap(item=>item.temas||[]).slice(0,15);return{title:`Ruta de ${course.nombre}`,summary:`## Punto de partida\n${course.descripcion||`Repaso de ${course.nombre}.`}\n\n## Temas priorizados\n${topics.map((topic,i)=>`${i+1}. **${topic.titulo}**`).join("\n")}`,keyConcepts:concepts,flashcards:concepts.concat(concepts.slice(0,2)).map(item=>({front:item.title,back:item.explanation})),quiz:topics.slice(0,6).map((topic,i)=>({question:`¿Cuál de estos temas pertenece a ${course.nombre}?`,options:[topic.titulo,...other.slice(i,i+3).map(item=>item.titulo)],correctIndex:0,explanation:`${topic.titulo} forma parte del temario de ${course.nombre}.`})).filter(item=>item.options.length===4),trueFalse:topics.slice(0,6).map(topic=>({statement:`“${topic.titulo}” forma parte del temario integrado de ${course.nombre}.`,correct:true,explanation:"Sí. Está incluido en el curso seleccionado."})),studyPlan:topics.slice(0,5).map((topic,i)=>({label:`Bloque ${i+1}: ${topic.titulo}`,duration:"25 min",objective:"Comprender la idea central y resolver 5 preguntas."})),audioScript:`Hoy estudiaremos ${course.nombre}. Empezaremos por ${topics.slice(0,4).map(item=>item.titulo).join(", ")}. Explica cada concepto con tus palabras, practica y revisa tus errores.`,sourceNote:reason==="SIN_SESION"?"Paquete local. Inicia sesión y activa la IA para analizar el archivo completo.":"Paquete local. Configura OPENAI_API_KEY en Vercel para analizar el archivo completo.",origin:"local"};}

  function normalizePack(raw){const course=courseById(state.setup.courseId);const concepts=Array.isArray(raw.keyConcepts)?raw.keyConcepts.slice(0,8).map(item=>({title:safeText(item.title,120),explanation:safeText(item.explanation,900),example:safeText(item.example,600)})).filter(item=>item.title):[];const flash=Array.isArray(raw.flashcards)?raw.flashcards.slice(0,12).map(item=>({front:safeText(item.front,240),back:safeText(item.back,900)})).filter(item=>item.front&&item.back):[];const quiz=Array.isArray(raw.quiz)?raw.quiz.slice(0,10).map(item=>({question:safeText(item.question,500),options:Array.isArray(item.options)?item.options.slice(0,4).map(option=>safeText(option,260)):[],correctIndex:Math.min(3,Math.max(0,Number(item.correctIndex)||0)),explanation:safeText(item.explanation,900)})).filter(item=>item.question&&item.options.length===4):[];const tf=Array.isArray(raw.trueFalse)?raw.trueFalse.slice(0,10).map(item=>({statement:safeText(item.statement,500),correct:Boolean(item.correct),explanation:safeText(item.explanation,900)})).filter(item=>item.statement):[];const plan=Array.isArray(raw.studyPlan)?raw.studyPlan.slice(0,8).map(item=>({label:safeText(item.label,160),duration:safeText(item.duration,40),objective:safeText(item.objective,500)})).filter(item=>item.label):[];return{id:uid(),title:safeText(raw.title,160)||`Ruta de ${course.nombre}`,summary:safeText(raw.summary,9000)||`Repaso de ${course.nombre}.`,keyConcepts:concepts,flashcards:flash,quiz,trueFalse:tf,studyPlan:plan,audioScript:safeText(raw.audioScript,5000)||safeText(raw.summary,3000),sourceNote:safeText(raw.sourceNote,800),origin:raw.origin==="ai"?"ai":"local",courseId:course.id,courseName:course.nombre,courseIcon:course.icono||"📘",examDate:state.setup.date,target:Math.min(100,Math.max(10,Number(state.setup.target)||80)),institution:safeText(state.setup.institution,100),level:state.setup.level,materialName:safeText(state.setup.file?.name||"Temario pegado",140),createdAt:new Date().toISOString()};}

  function openPack(id){if(!state.packs.some(pack=>pack.id===id))return;state.activeId=id;writeText(KEYS.active,id);state.module="home";state.activity=null;state.step=0;state.view="preparacion";writeText(KEYS.view,state.view);rerender();}
  function leavePack(){state.activeId="";writeText(KEYS.active,"");state.module="home";state.activity=null;rerender();}
  function renderWorkspace(){const pack=activePack();if(!pack)return renderHome();return `<section class="tutor-pack-workspace"><div class="tutor-pack-hero"><button class="tutor-back-button" onclick="volverInicioPreparacionIA()">← Espacios</button><div class="tutor-pack-course"><span>${pack.courseIcon||"📘"}</span><div><small>${esc(pack.courseName)}</small><h2>${esc(pack.title)}</h2><p>${esc(pack.materialName)}${pack.institution?` · ${esc(pack.institution)}`:""}</p></div></div><div class="tutor-pack-goals"><span><b>${daysUntil(pack.examDate)}</b>días</span><span><b>${pack.target}%</b>meta</span><span><b>${pack.quiz?.length||0}</b>preguntas</span></div></div>${pack.origin!=="ai"?`<div class="tutor-local-banner"><span>⚠</span><div><b>Modo de demostración local</b><p>${esc(pack.sourceNote)}</p></div><button onclick="iniciarPreparacionIA()">Probar con IA</button></div>`:""}${state.module==="home"?renderLessons(pack):renderModule(pack)}</section>`;}
  function moduleCard(id,icon,title,detail,color){return `<button class="tutor-module-card ${color}" onclick="abrirModuloIA('${id}')"><span>${icon}</span><div><b>${title}</b><small>${detail}</small></div><i>→</i></button>`;}
  function renderLessons(pack){return `<div class="tutor-next-lesson"><span class="tutor-eyebrow">SIGUIENTE LECCIÓN</span><h3>Elige cómo quieres aprender</h3><div class="tutor-learning-tabs"><button class="active">Aprender</button><button onclick="abrirModuloIA('truefalse')">Practicar</button><button onclick="abrirModuloIA('quiz')">Examen</button></div><div class="tutor-lesson-grid">${moduleCard("summary","📄","Resumen inteligente","Conceptos destacados y explicación ordenada","violet")}${moduleCard("concepts","🧠","Conceptos esenciales",`${pack.keyConcepts?.length||0} ideas con ejemplos`,"blue")}${moduleCard("audio","🎧","Audiolección","Escucha el resumen mientras repasas","green")}${moduleCard("cards","▣","Tarjetas de memoria",`${pack.flashcards?.length||0} tarjetas de repaso`,"orange")}${moduleCard("truefalse","✓","Verdadero o falso",`${pack.trueFalse?.length||0} afirmaciones explicadas`,"pink")}${moduleCard("quiz","📝","Simulacro IA",`${pack.quiz?.length||0} preguntas con explicación`,"cyan")}${moduleCard("plan","🗓️","Plan de estudio","Bloques organizados según tu fecha","yellow")}<button class="tutor-module-card ask" onclick="preguntarSobreMaterialIA()"><span>✦</span><div><b>Preguntar sobre el material</b><small>Conversa con Uni usando este contexto</small></div><i>→</i></button></div></div>`;}
  function openModule(module){if(!new Set(["summary","concepts","audio","cards","truefalse","quiz","plan"]).has(module))return;state.module=module;state.activity=null;if(module==="cards")state.activity={index:0,flipped:false};if(module==="truefalse"||module==="quiz")state.activity={index:0,score:0,answered:false,selected:null};rerender();}
  function closeModule(){window.speechSynthesis?.cancel?.();state.module="home";state.activity=null;rerender();}
  function formatMarkdown(text){return esc(text).replace(/^###\s+(.+)$/gm,"<h4>$1</h4>").replace(/^##\s+(.+)$/gm,"<h3>$1</h3>").replace(/^#\s+(.+)$/gm,"<h2>$1</h2>").replace(/\*\*([^*\n]+)\*\*/g,"<strong>$1</strong>").replace(/\n/g,"<br>");}
  function renderModule(pack){const names={summary:"Resumen inteligente",concepts:"Conceptos esenciales",audio:"Audiolección",cards:"Tarjetas de memoria",truefalse:"Verdadero o falso",quiz:"Simulacro IA",plan:"Plan de estudio"};return `<section class="tutor-module-view"><header><button onclick="cerrarModuloIA()">← Volver</button><div><span>LECCIÓN ACTIVA</span><h3>${names[state.module]}</h3></div><button onclick="preguntarSobreMaterialIA()">✦ Preguntar a Uni</button></header>${moduleContent(pack)}</section>`;}
  function moduleContent(pack){if(state.module==="summary")return `<article class="tutor-smart-summary"><div class="tutor-summary-toolbar"><span>📄 Generado desde ${esc(pack.materialName)}</span><button onclick="leerResumenPaquete()">🔊 Leer</button><button onclick="copiarResumenAApuntes()">＋ A apuntes</button></div><div class="tutor-summary-paper">${formatMarkdown(pack.summary)}</div>${pack.sourceNote?`<div class="tutor-source-note"><b>Alcance del análisis</b><p>${esc(pack.sourceNote)}</p></div>`:""}</article>`;if(state.module==="concepts")return `<div class="tutor-concept-list">${(pack.keyConcepts||[]).map((item,i)=>`<article><span>${String(i+1).padStart(2,"0")}</span><div><h4>${esc(item.title)}</h4><p>${esc(item.explanation)}</p>${item.example?`<aside><b>Ejemplo o aplicación</b>${esc(item.example)}</aside>`:""}</div></article>`).join("")||'<p class="tutor-empty-copy">No hay conceptos disponibles.</p>'}</div>`;if(state.module==="audio")return `<div class="tutor-audio-lesson"><div class="tutor-audio-visual"><span>✦</span><i></i><i></i><i></i><i></i><i></i></div><span class="tutor-eyebrow">AUDIOLECCIÓN IA</span><h3>${esc(pack.title)}</h3><p>Reproduce el resumen con la voz disponible en tu dispositivo.</p><div class="tutor-audio-actions"><button onclick="reproducirAudioPaquete()">▶ Reproducir</button><button onclick="detenerAudioPaquete()">■ Detener</button></div><details><summary>Ver guion</summary><p>${esc(pack.audioScript)}</p></details></div>`;if(state.module==="cards")return renderCards(pack);if(state.module==="truefalse")return renderQuestions(pack.trueFalse||[],true);if(state.module==="quiz")return renderQuestions(pack.quiz||[],false);return `<div class="tutor-study-plan">${(pack.studyPlan||[]).map((item,i)=>`<article><span>${i+1}</span><div><h4>${esc(item.label)}</h4><p>${esc(item.objective)}</p></div><b>${esc(item.duration)}</b></article>`).join("")||'<p class="tutor-empty-copy">No hay bloques disponibles.</p>'}<button onclick="guardarPlanEnAgendaIA()">＋ Guardar recordatorio en mi agenda</button></div>`;}
  function renderCards(pack){const cards=pack.flashcards||[];if(!cards.length)return'<p class="tutor-empty-copy">No hay tarjetas disponibles.</p>';const a=state.activity||{index:0,flipped:false};a.index=Math.min(cards.length-1,Math.max(0,a.index));state.activity=a;const card=cards[a.index];return `<div class="tutor-flashcards"><div class="tutor-activity-progress"><span style="width:${(a.index+1)/cards.length*100}%"></span></div><small>${a.index+1} de ${cards.length}</small><button class="tutor-flashcard ${a.flipped?"flipped":""}" onclick="voltearTarjetaIA()"><div><span>${a.flipped?"RESPUESTA":"CONCEPTO"}</span><h3>${esc(a.flipped?card.back:card.front)}</h3><small>${a.flipped?"Presiona para volver":"Presiona para revelar"}</small></div></button><div class="tutor-flashcard-actions"><button onclick="moverTarjetaIA(-1)" ${a.index===0?"disabled":""}>← Anterior</button><button onclick="moverTarjetaIA(1)">${a.index===cards.length-1?"Terminar":"Siguiente →"}</button></div></div>`;}
  function flipCard(){if(!state.activity)return;state.activity.flipped=!state.activity.flipped;rerender();}
  function moveCard(delta){const pack=activePack();if(!pack||!state.activity)return;const last=(pack.flashcards?.length||1)-1;if(delta>0&&state.activity.index>=last)return closeModule();state.activity.index=Math.min(last,Math.max(0,state.activity.index+delta));state.activity.flipped=false;rerender();}
  function renderQuestions(questions,isTF){if(!questions.length)return'<p class="tutor-empty-copy">No hay preguntas disponibles.</p>';const a=state.activity||{index:0,score:0,answered:false,selected:null};state.activity=a;if(a.index>=questions.length)return renderResult(questions.length,isTF);const q=questions[a.index];const correct=isTF?q.correct:q.correctIndex;const options=isTF?[{value:true,text:"Verdadero"},{value:false,text:"Falso"}]:q.options.map((text,i)=>({value:i,text}));return `<div class="tutor-quiz-engine"><div class="tutor-activity-progress"><span style="width:${(a.index+(a.answered?1:0))/questions.length*100}%"></span></div><div class="tutor-quiz-meta"><span>${a.index+1}/${questions.length}</span><b>${isTF?"VERDADERO O FALSO":"SIMULACRO PERSONALIZADO"}</b><span>${a.score} correctas</span></div><h3>${esc(isTF?q.statement:q.question)}</h3><div class="tutor-answer-list">${options.map((option,i)=>{const selected=a.answered&&a.selected===option.value;const good=a.answered&&option.value===correct;const bad=selected&&option.value!==correct;return `<button class="${good?"correct":bad?"incorrect":""}" ${a.answered?"disabled":""} onclick="${isTF?`responderVerdaderoFalsoIA(${option.value})`:`responderQuizIA(${option.value})`}"><span>${isTF?(i?"F":"V"):String.fromCharCode(65+i)}</span>${esc(option.text)}${good?"<i>✓</i>":bad?"<i>×</i>":""}</button>`;}).join("")}</div>${a.answered?`<div class="tutor-answer-explanation ${a.selected===correct?"success":"warning"}"><b>${a.selected===correct?"✓ Correcto":"Explicación"}</b><p>${esc(q.explanation)}</p></div><button class="tutor-next-question" onclick="siguientePreguntaIA()">${a.index===questions.length-1?"Ver resultado":"Siguiente pregunta →"}</button>`:'<p class="tutor-answer-hint">Elige una alternativa. La explicación aparecerá después.</p>'}</div>`;}
  function answerQuestion(value){const pack=activePack();if(!pack||!state.activity||state.activity.answered)return;const list=state.module==="truefalse"?pack.trueFalse||[]:pack.quiz||[];const q=list[state.activity.index];if(!q)return;const correct=state.module==="truefalse"?q.correct:q.correctIndex;state.activity.selected=value;state.activity.answered=true;if(value===correct)state.activity.score++;rerender();}
  function nextQuestion(){if(!state.activity?.answered)return;state.activity.index++;state.activity.answered=false;state.activity.selected=null;rerender();}
  function renderResult(total,isTF){const score=state.activity?.score||0;const pct=total?Math.round(score/total*100):0;return `<div class="tutor-quiz-result"><div class="tutor-result-ring" style="--result:${pct*3.6}deg"><div><b>${pct}%</b><span>resultado</span></div></div><span class="tutor-eyebrow">ACTIVIDAD COMPLETADA</span><h3>${score} de ${total} respuestas correctas</h3><p>${pct>=80?"Excelente. Revisa únicamente tus errores.":pct>=60?"Vas avanzando. Repasa y vuelve a intentarlo.":"Vuelve al resumen y las tarjetas antes de repetir."}</p><div><button onclick="reiniciarActividadIA()">Repetir actividad</button><button onclick="cerrarModuloIA()">Otra lección</button></div>${!isTF?`<button class="tutor-practice-bank-button" onclick="iniciarPracticaCursoNivel('${esc(activePack()?.courseId||"rm")}','todos',10)">Practicar 10 preguntas del banco UniPrep →</button>`:""}</div>`;}
  function resetActivity(){state.activity={index:0,score:0,answered:false,selected:null};rerender();}

  function askAboutPack(){const pack=activePack();if(!pack)return;window.__uniprepTutorPackContext={id:pack.id,title:pack.title,summary:pack.summary,concepts:pack.keyConcepts,courseId:pack.courseId};state.view="preguntar";writeText(KEYS.view,state.view);if(typeof window.cambiarAmbitoTutor==="function")window.cambiarAmbitoTutor("material");else rerender();setTimeout(()=>{const field=document.getElementById("tutor-question");if(field){field.value=`Tengo una duda sobre “${pack.title}”: `;field.focus();}},0);}
  function playAudio(){const pack=activePack();if(pack)window.leerTextoUniPrep?.(pack.audioScript||pack.summary);}
  function stopAudio(){window.speechSynthesis?.cancel?.();}
  function readSummary(){const pack=activePack();if(pack)window.leerTextoUniPrep?.(pack.summary);}
  function copySummary(){const pack=activePack();if(!pack)return;const notes=read("uniprep_course_notes_v1",{});notes[pack.courseId]=[String(notes[pack.courseId]||"").trim(),`${pack.title}\n${pack.summary}`].filter(Boolean).join("\n\n").slice(0,5000);write("uniprep_course_notes_v1",notes);window.registrarNotificacion?.({tipo:"estudio",titulo:"Resumen guardado",cuerpo:`El resumen de ${pack.courseName} se añadió a tus apuntes.`});}
  function savePlan(){const pack=activePack();if(!pack)return;window.registrarNotificacion?.({tipo:"estudio",titulo:`Plan de ${pack.courseName}`,cuerpo:`Tienes ${daysUntil(pack.examDate)} días para completar ${pack.studyPlan?.length||0} bloques.`});window.alert("Plan guardado como recordatorio de estudio en UniPrep.");}

  function renderLibrary(){return `<section class="tutor-library"><div class="tutor-section-title"><div><span>MIS MATERIALES IA</span><h2>Espacios de estudio guardados</h2><p>El archivo original no se almacena; aquí queda solamente el contenido generado.</p></div><button class="tutor-primary-button" onclick="iniciarPreparacionIA()">＋ Nuevo espacio</button></div>${state.packs.length?`<div class="tutor-pack-grid">${state.packs.map(pack=>`<div class="tutor-pack-wrapper">${renderPackCard(pack)}<button class="tutor-delete-pack" onclick="eliminarMaterialIA('${pack.id}')">Eliminar</button></div>`).join("")}</div>`:renderEmpty()}</section>`;}
  function deletePack(id){const pack=state.packs.find(item=>item.id===id);if(!pack||!window.confirm(`¿Eliminar “${pack.title}”?`))return;state.packs=state.packs.filter(item=>item.id!==id);if(state.activeId===id){state.activeId="";writeText(KEYS.active,"");}savePacks(false);window.UniPrepCloud?.deleteStudyPack?.(id);rerender();}
  function renderHistory(){const stored=read("uniprep_tutor_history_v1",[]);const messages=(Array.isArray(stored)?stored:[]).slice().reverse();return `<section class="tutor-history-view"><div class="tutor-section-title"><div><span>CONVERSACIONES</span><h2>Tu historial con Uni</h2><p>Se conserva una conversación breve dentro de tu cuenta en este dispositivo.</p></div>${messages.length?'<button onclick="limpiarHistorialTutorIA()">Limpiar historial</button>':""}</div>${messages.length?`<div class="tutor-history-list">${messages.map(message=>`<article class="${message.rol}"><span>${message.rol==="user"?"TÚ":message.rol==="ai"?"UNI · IA":"GUÍA LOCAL"}</span><p>${esc(safeText(message.texto,420))}</p><small>${message.tema?`${esc(message.tema)} · `:""}${message.fecha?new Date(message.fecha).toLocaleString("es-PE",{dateStyle:"medium",timeStyle:"short"}):""}</small></article>`).join("")}</div>`:'<div class="tutor-empty-history"><span>🕘</span><h3>Aún no hay conversaciones</h3><p>Hazle una pregunta a Uni y aparecerá aquí.</p><button onclick="UniprepTutorStudio.setView(\'preguntar\')">Comenzar conversación</button></div>'}</section>`;}
  function clearHistory(){window.limpiarTutor?.();setTimeout(rerender,0);}
  async function checkService(){const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),4500);try{const response=await fetch("/api/tutor",{headers:{Accept:"application/json"},signal:controller.signal});const data=await response.json().catch(()=>({}));const label=document.getElementById("tutor-service-status");if(label){label.textContent=data.available?"IA lista para ayudarte":"Guía local disponible";label.classList.toggle("online",Boolean(data.available));}}catch(_){const label=document.getElementById("tutor-service-status");if(label)label.textContent="Guía local disponible";}finally{clearTimeout(timeout);}}
  async function syncCloudPacks(){const cloud=await window.UniPrepCloud?.loadStudyPacks?.(12);if(!Array.isArray(cloud)||!cloud.length)return;const local=read(KEYS.packs,[]);const merged=[...(Array.isArray(local)?local:[]),...cloud].filter((pack,index,list)=>pack?.id&&list.findIndex(item=>item?.id===pack.id)===index).slice(0,12);state.packs=merged;savePacks(false);if(document.getElementById("tutor")?.classList.contains("active"))rerender();}

  document.addEventListener("uniprep:storage-scope-change",()=>{state.packs=read(KEYS.packs,[]);state.activeId=readText(KEYS.active,"");state.view=readText(KEYS.view,"preparacion");state.step=0;state.setup=freshSetup();state.module="home";state.activity=null;});
  document.addEventListener("uniprep:user-ready",syncCloudPacks);

  window.UniprepTutorStudio={renderIfNeeded,renderNav,setView,getActiveContext:()=>{const pack=activePack()||window.__uniprepTutorPackContext;return pack?`${pack.title}\n${pack.summary}\n${(pack.keyConcepts||pack.concepts||[]).map(item=>`${item.title}: ${item.explanation}`).join("\n")}`.slice(0,8000):"";}};
  Object.assign(window,{iniciarPreparacionIA:startPreparation,nextStep,prevStep,cancelPreparation,selectSubject,setExamDate,quickDate,updateGoal,selectLevel,processTutorFile:processFile,dropTutorFile:dropFile,removeTutorFile:removeFile,useBuiltInSyllabus:useBuiltIn,abrirPaqueteIA:openPack,volverInicioPreparacionIA:leavePack,abrirModuloIA:openModule,cerrarModuloIA:closeModule,voltearTarjetaIA:flipCard,moverTarjetaIA:moveCard,responderVerdaderoFalsoIA:value=>answerQuestion(Boolean(value)),responderQuizIA:value=>answerQuestion(Number(value)),siguientePreguntaIA:nextQuestion,reiniciarActividadIA:resetActivity,reproducirAudioPaquete:playAudio,detenerAudioPaquete:stopAudio,leerResumenPaquete:readSummary,copiarResumenAApuntes:copySummary,guardarPlanEnAgendaIA:savePlan,preguntarSobreMaterialIA:askAboutPack,eliminarMaterialIA:deletePack,limpiarHistorialTutorIA:clearHistory});
})();
