-- ============================================================
-- UNIPREP UGEL 2026 · RANKING TEMPORAL, REGIONES Y AVATARES
-- Ejecutar una sola vez en Supabase > SQL Editor.
-- ============================================================

alter table public.profiles add column if not exists procedencia text;
alter table public.profiles add column if not exists avatar_url text;
alter table public.profiles add column if not exists ranking_visible boolean not null default true;

-- Recupera el departamento que ya estaba guardado en Auth metadata.
update public.profiles as p
set procedencia = coalesce(nullif(p.procedencia, ''), u.raw_user_meta_data ->> 'procedencia'),
    avatar_url = coalesce(nullif(p.avatar_url, ''), u.raw_user_meta_data ->> 'avatar_url')
from auth.users as u
where p.id = u.id;

create or replace function public.sincronizar_metadata_uniprep()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.profiles
  set procedencia = coalesce(new.raw_user_meta_data ->> 'procedencia', procedencia),
      avatar_url = coalesce(new.raw_user_meta_data ->> 'avatar_url', avatar_url)
  where id = new.id;
  return new;
end;
$$;

drop trigger if exists sincronizar_metadata_uniprep_trigger on auth.users;
create trigger sincronizar_metadata_uniprep_trigger
after insert or update of raw_user_meta_data on auth.users
for each row execute function public.sincronizar_metadata_uniprep();

create table if not exists public.score_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null default 'practica',
  points integer not null default 0 check (points between 0 and 5000),
  correct_answers integer not null default 0 check (correct_answers between 0 and 500),
  wrong_answers integer not null default 0 check (wrong_answers between 0 and 500),
  blank_answers integer not null default 0 check (blank_answers between 0 and 500),
  total_answers integer not null default 0 check (total_answers between 0 and 500),
  exam_score numeric(12,3),
  exam_max numeric(12,3),
  exam_percent numeric(5,2) check (exam_percent between 0 and 100),
  exam_scale text not null default '',
  university_id text not null default 'general',
  created_at timestamptz not null default now(),
  constraint score_events_totals_ok check (correct_answers + wrong_answers + blank_answers <= total_answers)
);

alter table public.score_events add column if not exists exam_max numeric(12,3);
alter table public.score_events add column if not exists exam_percent numeric(5,2);

create index if not exists score_events_user_date_idx on public.score_events(user_id, created_at desc);
create index if not exists score_events_date_idx on public.score_events(created_at desc);

alter table public.score_events enable row level security;
drop policy if exists "score_events_insert_own" on public.score_events;
create policy "score_events_insert_own" on public.score_events for insert to authenticated
with check (auth.uid() = user_id);
drop policy if exists "score_events_select_own" on public.score_events;
create policy "score_events_select_own" on public.score_events for select to authenticated
using (auth.uid() = user_id);

-- El ranking devuelve solo nombre público abreviado en la interfaz y datos agregados.
create or replace function public.obtener_ranking_uniprep_v2(
  p_periodo text default 'semana',
  p_region text default null
)
returns table (
  id uuid,
  nombre text,
  carrera text,
  procedencia text,
  avatar_url text,
  puntos_periodo bigint,
  preguntas_periodo bigint,
  correctas_periodo bigint,
  precision_periodo numeric,
  mejor_simulacro numeric,
  escala_simulacro text
)
language sql
stable
security definer
set search_path = public
as $$
  with parametros as (
    select case lower(coalesce(p_periodo, 'semana'))
      when 'dia' then date_trunc('day', now() at time zone 'America/Lima') at time zone 'America/Lima'
      when 'semana' then date_trunc('week', now() at time zone 'America/Lima') at time zone 'America/Lima'
      when 'mes' then date_trunc('month', now() at time zone 'America/Lima') at time zone 'America/Lima'
      else to_timestamp(0)
    end as desde
  ), eventos as (
    select e.user_id,
      sum(e.points)::bigint as puntos,
      sum(e.total_answers)::bigint as preguntas,
      sum(e.correct_answers)::bigint as correctas,
      max(e.exam_percent) as mejor,
      (array_agg(
        concat(
          trim(to_char(e.exam_score, 'FM999999990.000')),
          case when e.exam_max is not null then concat(' de ', trim(to_char(e.exam_max, 'FM999999990.000'))) else '' end,
          case when nullif(e.exam_scale, '') is not null then concat(' · ', e.exam_scale) else '' end
        ) order by e.exam_percent desc nulls last
      ) filter (where e.exam_score is not null and e.exam_percent is not null))[1] as escala
    from public.score_events e, parametros x
    where e.created_at >= x.desde
    group by e.user_id
  )
  select p.id,
    coalesce(nullif(p.nombre, ''), 'Estudiante UniPrep')::text,
    coalesce(nullif(p.carrera, ''), 'Preuniversitario')::text,
    coalesce(nullif(p.procedencia, ''), 'Sin región')::text,
    coalesce(p.avatar_url, '')::text,
    (case when lower(coalesce(p_periodo, 'semana')) = 'total'
      then greatest(coalesce(e.puntos, 0), coalesce(p.xp, 0)::bigint)
      else coalesce(e.puntos, 0) end)::bigint,
    (case when lower(coalesce(p_periodo, 'semana')) = 'total'
      then greatest(coalesce(e.preguntas, 0), coalesce(p.respuestas_totales, 0)::bigint)
      else coalesce(e.preguntas, 0) end)::bigint,
    (case when lower(coalesce(p_periodo, 'semana')) = 'total'
      then greatest(coalesce(e.correctas, 0), coalesce(p.respuestas_correctas, 0)::bigint)
      else coalesce(e.correctas, 0) end)::bigint,
    (case
      when lower(coalesce(p_periodo, 'semana')) = 'total' and coalesce(p.respuestas_totales, 0) > 0
        then round((p.respuestas_correctas::numeric / p.respuestas_totales::numeric) * 100, 1)
      when coalesce(e.preguntas, 0) > 0
        then round((e.correctas::numeric / e.preguntas::numeric) * 100, 1)
      else 0 end)::numeric,
    coalesce(e.mejor, 0)::numeric,
    coalesce(e.escala, '')::text
  from public.profiles p
  left join eventos e on e.user_id = p.id
  where coalesce(p.ranking_visible, true)
    and (p_region is null or lower(coalesce(p.procedencia, '')) = lower(p_region))
  order by 6 desc, 8 desc, 2 asc
  limit 500;
$$;

revoke all on function public.obtener_ranking_uniprep_v2(text, text) from public;
grant execute on function public.obtener_ranking_uniprep_v2(text, text) to authenticated;

-- Bucket público para que la propia foto pueda verse también en el ranking.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('avatars', 'avatars', true, 2097152, array['image/webp','image/jpeg','image/png'])
on conflict (id) do update set public = true, file_size_limit = 2097152,
  allowed_mime_types = array['image/webp','image/jpeg','image/png'];

drop policy if exists "avatars_public_read" on storage.objects;
create policy "avatars_public_read" on storage.objects for select to public
using (bucket_id = 'avatars');
drop policy if exists "avatars_insert_own" on storage.objects;
create policy "avatars_insert_own" on storage.objects for insert to authenticated
with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "avatars_update_own" on storage.objects;
create policy "avatars_update_own" on storage.objects for update to authenticated
using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text)
with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "avatars_delete_own" on storage.objects;
create policy "avatars_delete_own" on storage.objects for delete to authenticated
using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

notify pgrst, 'reload schema';
