-- =====================================================================
-- UNIPREP UGEL · EVOLUCIÓN 2026.18
-- Preferencias, Tutor IA, materiales y orientación sincronizados.
-- Ejecutar UNA VEZ en Supabase > SQL Editor, después del script de ranking.
-- Todas las tablas tienen RLS: cada estudiante accede únicamente a lo suyo.
-- =====================================================================

create table if not exists public.user_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  visual jsonb not null default '{}'::jsonb,
  tutor jsonb not null default '{}'::jsonb,
  accessibility jsonb not null default '{}'::jsonb,
  intro_seen_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint user_preferences_visual_object check (jsonb_typeof(visual) = 'object'),
  constraint user_preferences_tutor_object check (jsonb_typeof(tutor) = 'object'),
  constraint user_preferences_accessibility_object check (jsonb_typeof(accessibility) = 'object')
);

create table if not exists public.ai_study_packs (
  user_id uuid not null references auth.users(id) on delete cascade,
  id text not null check (char_length(id) between 3 and 100),
  title text not null default '' check (char_length(title) <= 180),
  course_id text not null default '' check (char_length(course_id) <= 60),
  content jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, id),
  constraint ai_study_packs_content_object check (jsonb_typeof(content) = 'object')
);

create table if not exists public.vocational_results (
  user_id uuid primary key references auth.users(id) on delete cascade,
  result jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  constraint vocational_results_object check (jsonb_typeof(result) = 'object')
);

create table if not exists public.ai_feedback (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  message_id text not null default '' check (char_length(message_id) <= 100),
  rating smallint not null check (rating in (-1, 1)),
  context jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint ai_feedback_context_object check (jsonb_typeof(context) = 'object')
);

create table if not exists public.ai_usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  request_type text not null default 'chat' check (char_length(request_type) <= 40),
  model text not null default '' check (char_length(model) <= 80),
  input_tokens integer not null default 0 check (input_tokens between 0 and 2000000),
  output_tokens integer not null default 0 check (output_tokens between 0 and 2000000),
  estimated_cost_usd numeric(14,8) not null default 0 check (estimated_cost_usd >= 0),
  created_at timestamptz not null default now()
);

create index if not exists ai_study_packs_user_updated_idx on public.ai_study_packs(user_id, updated_at desc);
create index if not exists ai_feedback_user_date_idx on public.ai_feedback(user_id, created_at desc);
create index if not exists ai_usage_events_user_date_idx on public.ai_usage_events(user_id, created_at desc);

alter table public.user_preferences enable row level security;
alter table public.ai_study_packs enable row level security;
alter table public.vocational_results enable row level security;
alter table public.ai_feedback enable row level security;
alter table public.ai_usage_events enable row level security;

drop policy if exists "user_preferences_own" on public.user_preferences;
create policy "user_preferences_own" on public.user_preferences
for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "ai_study_packs_own" on public.ai_study_packs;
create policy "ai_study_packs_own" on public.ai_study_packs
for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "vocational_results_own" on public.vocational_results;
create policy "vocational_results_own" on public.vocational_results
for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "ai_feedback_insert_own" on public.ai_feedback;
create policy "ai_feedback_insert_own" on public.ai_feedback
for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "ai_feedback_select_own" on public.ai_feedback;
create policy "ai_feedback_select_own" on public.ai_feedback
for select to authenticated using (auth.uid() = user_id);

drop policy if exists "ai_usage_events_insert_own" on public.ai_usage_events;
create policy "ai_usage_events_insert_own" on public.ai_usage_events
for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "ai_usage_events_select_own" on public.ai_usage_events;
create policy "ai_usage_events_select_own" on public.ai_usage_events
for select to authenticated using (auth.uid() = user_id);

-- Impide que una cuenta acumule cientos de paquetes por error desde el cliente.
create or replace function public.limitar_paquetes_uniprep()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if (select count(*) from public.ai_study_packs where user_id = new.user_id) >= 24
     and not exists (select 1 from public.ai_study_packs where user_id = new.user_id and id = new.id) then
    raise exception 'Límite de 24 materiales IA por estudiante';
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists limitar_paquetes_uniprep_trigger on public.ai_study_packs;
create trigger limitar_paquetes_uniprep_trigger
before insert or update on public.ai_study_packs
for each row execute function public.limitar_paquetes_uniprep();

revoke all on public.user_preferences, public.ai_study_packs, public.vocational_results, public.ai_feedback, public.ai_usage_events from anon;
grant select, insert, update, delete on public.user_preferences, public.ai_study_packs, public.vocational_results to authenticated;
grant select, insert on public.ai_feedback, public.ai_usage_events to authenticated;
grant usage, select on sequence public.ai_feedback_id_seq to authenticated;
grant usage, select on sequence public.ai_usage_events_id_seq to authenticated;

notify pgrst, 'reload schema';
