-- ============================================================================
-- UNIPREP 2 · INSTALADOR COMPLETO SUPABASE · 2026.23
-- Ejecutar una sola vez desde Supabase > SQL Editor.
-- Es idempotente: puede volver a ejecutarse para completar objetos faltantes.
-- Incluye cuenta, progreso, agenda, ranking, Tutor IA, apariencia y Universo.
-- ============================================================================

begin;

-- --------------------------------------------------------------------------
-- 1. PERFIL Y DATOS ACADÉMICOS PRINCIPALES
-- --------------------------------------------------------------------------

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nombre text not null default 'Estudiante UniPrep',
  correo text not null default '',
  carrera text not null default '',
  universidad text not null default '',
  procedencia text not null default '',
  avatar_url text not null default '',
  nivel integer not null default 1,
  xp integer not null default 0,
  monedas integer not null default 0,
  racha integer not null default 0,
  record_racha integer not null default 0,
  ultimo_dia_estudio date,
  ejercicios integer not null default 0,
  respuestas_correctas integer not null default 0,
  respuestas_totales integer not null default 0,
  precision numeric(5,2) not null default 0,
  ranking integer,
  simulacros integer not null default 0,
  ranking_visible boolean not null default true,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

alter table public.profiles add column if not exists nombre text not null default 'Estudiante UniPrep';
alter table public.profiles add column if not exists correo text not null default '';
alter table public.profiles add column if not exists carrera text not null default '';
alter table public.profiles add column if not exists universidad text not null default '';
alter table public.profiles add column if not exists procedencia text not null default '';
alter table public.profiles add column if not exists avatar_url text not null default '';
alter table public.profiles add column if not exists nivel integer not null default 1;
alter table public.profiles add column if not exists xp integer not null default 0;
alter table public.profiles add column if not exists monedas integer not null default 0;
alter table public.profiles add column if not exists racha integer not null default 0;
alter table public.profiles add column if not exists record_racha integer not null default 0;
alter table public.profiles add column if not exists ultimo_dia_estudio date;
alter table public.profiles add column if not exists ejercicios integer not null default 0;
alter table public.profiles add column if not exists respuestas_correctas integer not null default 0;
alter table public.profiles add column if not exists respuestas_totales integer not null default 0;
alter table public.profiles add column if not exists precision numeric(5,2) not null default 0;
alter table public.profiles add column if not exists ranking integer;
alter table public.profiles add column if not exists simulacros integer not null default 0;
alter table public.profiles add column if not exists ranking_visible boolean not null default true;
alter table public.profiles add column if not exists creado_en timestamptz not null default now();
alter table public.profiles add column if not exists actualizado_en timestamptz not null default now();

create table if not exists public.course_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id text not null check (char_length(course_id) between 1 and 60),
  progress numeric(5,2) not null default 0 check (progress between 0 and 100),
  completed_exercises integer not null default 0 check (completed_exercises >= 0),
  correct_answers integer not null default 0 check (correct_answers >= 0),
  total_answers integer not null default 0 check (total_answers >= 0),
  last_topic_index integer not null default 0 check (last_topic_index >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, course_id),
  constraint course_progress_answers_ok check (correct_answers <= total_answers)
);

create table if not exists public.activities (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  activity_type text not null default 'actividad' check (char_length(activity_type) <= 60),
  title text not null default 'Actividad' check (char_length(title) <= 180),
  description text not null default '' check (char_length(description) <= 1000),
  xp_earned integer not null default 0 check (xp_earned between 0 and 5000),
  created_at timestamptz not null default now()
);

create table if not exists public.agenda_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 180),
  description text not null default '' check (char_length(description) <= 1500),
  event_date date not null,
  start_time time,
  end_time time,
  event_type text not null default 'estudio' check (char_length(event_type) <= 40),
  completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint agenda_time_order check (end_time is null or start_time is null or end_time >= start_time)
);

create index if not exists course_progress_user_idx on public.course_progress(user_id);
create unique index if not exists course_progress_user_course_uidx
  on public.course_progress(user_id, course_id);
create index if not exists activities_user_date_idx on public.activities(user_id, created_at desc);
create index if not exists agenda_events_user_date_idx on public.agenda_events(user_id, event_date, start_time);

-- --------------------------------------------------------------------------
-- 2. RANKING POR PERIODO Y RESULTADOS NORMALIZADOS
-- --------------------------------------------------------------------------

create table if not exists public.score_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null default 'practica' check (char_length(event_type) <= 40),
  points integer not null default 0 check (points between 0 and 5000),
  correct_answers integer not null default 0 check (correct_answers between 0 and 500),
  wrong_answers integer not null default 0 check (wrong_answers between 0 and 500),
  blank_answers integer not null default 0 check (blank_answers between 0 and 500),
  total_answers integer not null default 0 check (total_answers between 0 and 500),
  exam_score numeric(12,3),
  exam_max numeric(12,3),
  exam_percent numeric(5,2) check (exam_percent between 0 and 100),
  exam_scale text not null default '' check (char_length(exam_scale) <= 80),
  university_id text not null default 'general' check (char_length(university_id) <= 40),
  created_at timestamptz not null default now(),
  constraint score_events_totals_ok check (correct_answers + wrong_answers + blank_answers <= total_answers)
);

alter table public.score_events add column if not exists exam_max numeric(12,3);
alter table public.score_events add column if not exists exam_percent numeric(5,2);
alter table public.score_events add column if not exists exam_scale text not null default '';
alter table public.score_events add column if not exists university_id text not null default 'general';

create index if not exists score_events_user_date_idx on public.score_events(user_id, created_at desc);
create index if not exists score_events_date_idx on public.score_events(created_at desc);

-- --------------------------------------------------------------------------
-- 3. APARIENCIA, TUTOR IA Y ORIENTACIÓN
-- --------------------------------------------------------------------------

create table if not exists public.user_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  visual jsonb not null default '{}'::jsonb,
  tutor jsonb not null default '{}'::jsonb,
  accessibility jsonb not null default '{}'::jsonb,
  intro_seen_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint user_preferences_visual_object check (jsonb_typeof(visual) = 'object'),
  constraint user_preferences_tutor_object check (jsonb_typeof(tutor) = 'object'),
  constraint user_preferences_accessibility_object check (jsonb_typeof(accessibility) = 'object')
);

create table if not exists public.ai_study_packs (
  user_id uuid not null references auth.users(id) on delete cascade,
  id text not null check (char_length(id) between 3 and 100),
  title text not null default '' check (char_length(title) <= 180),
  course_id text not null default '' check (char_length(course_id) <= 60),
  content jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, id),
  constraint ai_study_packs_content_object check (jsonb_typeof(content) = 'object')
);

create table if not exists public.vocational_results (
  user_id uuid primary key references auth.users(id) on delete cascade,
  result jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  constraint vocational_results_object check (jsonb_typeof(result) = 'object')
);

create table if not exists public.ai_feedback (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  message_id text not null default '' check (char_length(message_id) <= 100),
  rating smallint not null check (rating in (-1, 1)),
  context jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint ai_feedback_context_object check (jsonb_typeof(context) = 'object')
);

create table if not exists public.ai_usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  request_type text not null default 'chat' check (char_length(request_type) <= 40),
  model text not null default '' check (char_length(model) <= 80),
  input_tokens integer not null default 0 check (input_tokens between 0 and 2000000),
  output_tokens integer not null default 0 check (output_tokens between 0 and 2000000),
  estimated_cost_usd numeric(14,8) not null default 0 check (estimated_cost_usd >= 0),
  created_at timestamptz not null default now()
);

create index if not exists ai_study_packs_user_updated_idx on public.ai_study_packs(user_id, updated_at desc);
create index if not exists ai_feedback_user_date_idx on public.ai_feedback(user_id, created_at desc);
create index if not exists ai_usage_events_user_date_idx on public.ai_usage_events(user_id, created_at desc);

-- --------------------------------------------------------------------------
-- 4. UNIVERSO UNIPREP
-- --------------------------------------------------------------------------

create table if not exists public.universe_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  constraint universe_profiles_state_object check (jsonb_typeof(state) = 'object')
);

create table if not exists public.universe_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null check (char_length(event_type) between 1 and 60),
  event_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint universe_events_data_object check (jsonb_typeof(event_data) = 'object')
);

create index if not exists universe_events_user_date_idx on public.universe_events(user_id, created_at desc);
create index if not exists universe_events_type_date_idx on public.universe_events(event_type, created_at desc);

-- --------------------------------------------------------------------------
-- 5. FUNCIONES Y DISPARADORES
-- --------------------------------------------------------------------------

create or replace function public.touch_uniprep_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists course_progress_touch on public.course_progress;
create trigger course_progress_touch before update on public.course_progress
for each row execute function public.touch_uniprep_updated_at();

drop trigger if exists agenda_events_touch on public.agenda_events;
create trigger agenda_events_touch before update on public.agenda_events
for each row execute function public.touch_uniprep_updated_at();

drop trigger if exists user_preferences_touch on public.user_preferences;
create trigger user_preferences_touch before update on public.user_preferences
for each row execute function public.touch_uniprep_updated_at();

drop trigger if exists ai_study_packs_touch on public.ai_study_packs;
create trigger ai_study_packs_touch before update on public.ai_study_packs
for each row execute function public.touch_uniprep_updated_at();

drop trigger if exists vocational_results_touch on public.vocational_results;
create trigger vocational_results_touch before update on public.vocational_results
for each row execute function public.touch_uniprep_updated_at();

drop trigger if exists universe_profiles_touch on public.universe_profiles;
create trigger universe_profiles_touch before update on public.universe_profiles
for each row execute function public.touch_uniprep_updated_at();

create or replace function public.touch_uniprep_profile()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.actualizado_en := now();
  return new;
end;
$$;

drop trigger if exists profiles_touch on public.profiles;
create trigger profiles_touch before update on public.profiles
for each row execute function public.touch_uniprep_profile();

-- Crea y mantiene el perfil a partir de Auth sin guardar contraseñas.
create or replace function public.sincronizar_usuario_uniprep()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  metadata jsonb := coalesce(new.raw_user_meta_data, '{}'::jsonb);
begin
  insert into public.profiles (
    id, nombre, correo, carrera, universidad, procedencia, avatar_url
  ) values (
    new.id,
    coalesce(nullif(metadata ->> 'nombre', ''), nullif(split_part(coalesce(new.email, ''), '@', 1), ''), 'Estudiante UniPrep'),
    coalesce(new.email, ''),
    coalesce(metadata ->> 'carrera', ''),
    coalesce(metadata ->> 'universidad', ''),
    coalesce(metadata ->> 'procedencia', ''),
    coalesce(metadata ->> 'avatar_url', '')
  )
  on conflict (id) do update set
    correo = excluded.correo,
    nombre = coalesce(nullif(excluded.nombre, ''), public.profiles.nombre),
    carrera = coalesce(nullif(excluded.carrera, ''), public.profiles.carrera),
    universidad = coalesce(nullif(excluded.universidad, ''), public.profiles.universidad),
    procedencia = coalesce(nullif(excluded.procedencia, ''), public.profiles.procedencia),
    avatar_url = coalesce(nullif(excluded.avatar_url, ''), public.profiles.avatar_url),
    actualizado_en = now();
  return new;
end;
$$;

drop trigger if exists sincronizar_metadata_uniprep_trigger on auth.users;
drop trigger if exists sincronizar_usuario_uniprep_trigger on auth.users;
create trigger sincronizar_usuario_uniprep_trigger
after insert or update of email, raw_user_meta_data on auth.users
for each row execute function public.sincronizar_usuario_uniprep();

-- Completa perfiles de cuentas creadas antes de instalar este script.
insert into public.profiles (id, nombre, correo, carrera, universidad, procedencia, avatar_url)
select
  u.id,
  coalesce(nullif(u.raw_user_meta_data ->> 'nombre', ''), nullif(split_part(coalesce(u.email, ''), '@', 1), ''), 'Estudiante UniPrep'),
  coalesce(u.email, ''),
  coalesce(u.raw_user_meta_data ->> 'carrera', ''),
  coalesce(u.raw_user_meta_data ->> 'universidad', ''),
  coalesce(u.raw_user_meta_data ->> 'procedencia', ''),
  coalesce(u.raw_user_meta_data ->> 'avatar_url', '')
from auth.users u
on conflict (id) do nothing;

create or replace function public.limitar_paquetes_uniprep()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if (select count(*) from public.ai_study_packs where user_id = new.user_id) >= 24
     and not exists (select 1 from public.ai_study_packs where user_id = new.user_id and id = new.id) then
    raise exception 'Límite de 24 materiales IA por estudiante';
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists limitar_paquetes_uniprep_trigger on public.ai_study_packs;
create trigger limitar_paquetes_uniprep_trigger
before insert or update on public.ai_study_packs
for each row execute function public.limitar_paquetes_uniprep();

-- Ranking: solo devuelve campos públicos y resultados agregados.
create or replace function public.obtener_ranking_uniprep_v2(
  p_periodo text default 'semana',
  p_region text default null
)
returns table (
  id uuid,
  nombre text,
  carrera text,
  procedencia text,
  avatar_url text,
  puntos_periodo bigint,
  preguntas_periodo bigint,
  correctas_periodo bigint,
  precision_periodo numeric,
  mejor_simulacro numeric,
  escala_simulacro text
)
language sql
stable
security definer
set search_path = public
as $$
  with parametros as (
    select case lower(coalesce(p_periodo, 'semana'))
      when 'dia' then date_trunc('day', now() at time zone 'America/Lima') at time zone 'America/Lima'
      when 'semana' then date_trunc('week', now() at time zone 'America/Lima') at time zone 'America/Lima'
      when 'mes' then date_trunc('month', now() at time zone 'America/Lima') at time zone 'America/Lima'
      else to_timestamp(0)
    end as desde
  ), eventos as (
    select e.user_id,
      sum(e.points)::bigint as puntos,
      sum(e.total_answers)::bigint as preguntas,
      sum(e.correct_answers)::bigint as correctas,
      max(e.exam_percent) as mejor,
      (array_agg(
        concat(
          trim(to_char(e.exam_score, 'FM999999990.000')),
          case when e.exam_max is not null then concat(' de ', trim(to_char(e.exam_max, 'FM999999990.000'))) else '' end,
          case when nullif(e.exam_scale, '') is not null then concat(' · ', e.exam_scale) else '' end
        ) order by e.exam_percent desc nulls last
      ) filter (where e.exam_score is not null and e.exam_percent is not null))[1] as escala
    from public.score_events e, parametros x
    where e.created_at >= x.desde
    group by e.user_id
  )
  select p.id,
    coalesce(nullif(p.nombre, ''), 'Estudiante UniPrep')::text,
    coalesce(nullif(p.carrera, ''), 'Preuniversitario')::text,
    coalesce(nullif(p.procedencia, ''), 'Sin región')::text,
    coalesce(p.avatar_url, '')::text,
    (case when lower(coalesce(p_periodo, 'semana')) = 'total'
      then greatest(coalesce(e.puntos, 0), coalesce(p.xp, 0)::bigint)
      else coalesce(e.puntos, 0) end)::bigint,
    (case when lower(coalesce(p_periodo, 'semana')) = 'total'
      then greatest(coalesce(e.preguntas, 0), coalesce(p.respuestas_totales, 0)::bigint)
      else coalesce(e.preguntas, 0) end)::bigint,
    (case when lower(coalesce(p_periodo, 'semana')) = 'total'
      then greatest(coalesce(e.correctas, 0), coalesce(p.respuestas_correctas, 0)::bigint)
      else coalesce(e.correctas, 0) end)::bigint,
    (case
      when lower(coalesce(p_periodo, 'semana')) = 'total' and coalesce(p.respuestas_totales, 0) > 0
        then round((p.respuestas_correctas::numeric / p.respuestas_totales::numeric) * 100, 1)
      when coalesce(e.preguntas, 0) > 0
        then round((e.correctas::numeric / e.preguntas::numeric) * 100, 1)
      else 0 end)::numeric,
    coalesce(e.mejor, 0)::numeric,
    coalesce(e.escala, '')::text
  from public.profiles p
  left join eventos e on e.user_id = p.id
  where coalesce(p.ranking_visible, true)
    and (p_region is null or lower(coalesce(p.procedencia, '')) = lower(p_region))
  order by 6 desc, 8 desc, 2 asc
  limit 500;
$$;

-- Eliminación solicitada por el propio usuario autenticado.
create or replace function public.eliminar_mi_cuenta_uniprep()
returns boolean
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  usuario_id uuid := auth.uid();
begin
  if usuario_id is null then
    return false;
  end if;
  delete from auth.users where id = usuario_id;
  return found;
end;
$$;

-- --------------------------------------------------------------------------
-- 6. SEGURIDAD POR FILA (RLS)
-- --------------------------------------------------------------------------

alter table public.profiles enable row level security;
alter table public.course_progress enable row level security;
alter table public.activities enable row level security;
alter table public.agenda_events enable row level security;
alter table public.score_events enable row level security;
alter table public.user_preferences enable row level security;
alter table public.ai_study_packs enable row level security;
alter table public.vocational_results enable row level security;
alter table public.ai_feedback enable row level security;
alter table public.ai_usage_events enable row level security;
alter table public.universe_profiles enable row level security;
alter table public.universe_events enable row level security;

drop policy if exists profiles_select_own on public.profiles;
create policy profiles_select_own on public.profiles for select to authenticated using (auth.uid() = id);
drop policy if exists profiles_insert_own on public.profiles;
create policy profiles_insert_own on public.profiles for insert to authenticated with check (auth.uid() = id);
drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own on public.profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists course_progress_own on public.course_progress;
create policy course_progress_own on public.course_progress for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists activities_own on public.activities;
create policy activities_own on public.activities for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists agenda_events_own on public.agenda_events;
create policy agenda_events_own on public.agenda_events for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists score_events_insert_own on public.score_events;
create policy score_events_insert_own on public.score_events for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists score_events_select_own on public.score_events;
create policy score_events_select_own on public.score_events for select to authenticated using (auth.uid() = user_id);

drop policy if exists user_preferences_own on public.user_preferences;
create policy user_preferences_own on public.user_preferences for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists ai_study_packs_own on public.ai_study_packs;
create policy ai_study_packs_own on public.ai_study_packs for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists vocational_results_own on public.vocational_results;
create policy vocational_results_own on public.vocational_results for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists ai_feedback_insert_own on public.ai_feedback;
create policy ai_feedback_insert_own on public.ai_feedback for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists ai_feedback_select_own on public.ai_feedback;
create policy ai_feedback_select_own on public.ai_feedback for select to authenticated using (auth.uid() = user_id);

drop policy if exists ai_usage_events_insert_own on public.ai_usage_events;
create policy ai_usage_events_insert_own on public.ai_usage_events for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists ai_usage_events_select_own on public.ai_usage_events;
create policy ai_usage_events_select_own on public.ai_usage_events for select to authenticated using (auth.uid() = user_id);

drop policy if exists universe_profiles_own on public.universe_profiles;
create policy universe_profiles_own on public.universe_profiles for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists universe_events_insert_own on public.universe_events;
create policy universe_events_insert_own on public.universe_events for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists universe_events_select_own on public.universe_events;
create policy universe_events_select_own on public.universe_events for select to authenticated using (auth.uid() = user_id);

-- --------------------------------------------------------------------------
-- 7. FOTO DE PERFIL
-- --------------------------------------------------------------------------

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('avatars', 'avatars', true, 2097152, array['image/webp','image/jpeg','image/png'])
on conflict (id) do update set public = true, file_size_limit = 2097152,
  allowed_mime_types = array['image/webp','image/jpeg','image/png'];

drop policy if exists avatars_public_read on storage.objects;
create policy avatars_public_read on storage.objects for select to public using (bucket_id = 'avatars');
drop policy if exists avatars_insert_own on storage.objects;
create policy avatars_insert_own on storage.objects for insert to authenticated
with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists avatars_update_own on storage.objects;
create policy avatars_update_own on storage.objects for update to authenticated
using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text)
with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists avatars_delete_own on storage.objects;
create policy avatars_delete_own on storage.objects for delete to authenticated
using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

-- --------------------------------------------------------------------------
-- 8. PERMISOS DE API
-- --------------------------------------------------------------------------

revoke all on public.profiles, public.course_progress, public.activities, public.agenda_events,
  public.score_events, public.user_preferences, public.ai_study_packs, public.vocational_results,
  public.ai_feedback, public.ai_usage_events, public.universe_profiles, public.universe_events from anon;

grant select, insert, update on public.profiles to authenticated;
grant select, insert, update, delete on public.course_progress, public.activities, public.agenda_events,
  public.user_preferences, public.ai_study_packs, public.vocational_results, public.universe_profiles to authenticated;
grant select, insert on public.score_events, public.ai_feedback, public.ai_usage_events, public.universe_events to authenticated;

revoke all on function public.obtener_ranking_uniprep_v2(text, text) from public;
grant execute on function public.obtener_ranking_uniprep_v2(text, text) to authenticated;
revoke all on function public.eliminar_mi_cuenta_uniprep() from public;
grant execute on function public.eliminar_mi_cuenta_uniprep() to authenticated;

do $$
declare
  seq_name text;
begin
  foreach seq_name in array array[
    'activities_id_seq','agenda_events_id_seq','score_events_id_seq',
    'ai_feedback_id_seq','ai_usage_events_id_seq','universe_events_id_seq'
  ] loop
    if to_regclass('public.' || seq_name) is not null then
      execute format('grant usage, select on sequence public.%I to authenticated', seq_name);
    end if;
  end loop;
end;
$$;

notify pgrst, 'reload schema';

commit;

-- FIN. No pegues claves privadas dentro de este archivo.
