#!/usr/bin/env node
"use strict";

const fs=require("fs"), path=require("path");
const ROOT=path.resolve(__dirname,".."), BANK=path.join(ROOT,"json","quiz-cursos");
const levels=["basico","intermedio","avanzado","admision"];
const distribution={basico:10,intermedio:10,avanzado:10,admision:15,total:45};
const levelCode={basico:"B",intermedio:"I",avanzado:"A",admision:"R"};

function rotate(values,seed){
  const correct=String(values[0]);
  const clean=[correct,...new Set(values.slice(1).map(String).filter(value=>value!==correct))];
  for(const fallback of ["0","1","−1","2","no se puede determinar","ninguna de las anteriores"]){
    if(clean.length>=4)break;
    if(!clean.includes(fallback))clean.push(fallback);
  }
  if(clean.length<4)throw Error(`Opciones inválidas: ${values}`);
  const four=clean.slice(0,4),s=seed%4,out=four.slice(s).concat(four.slice(0,s));
  return {alternativas:out,respuesta:out.indexOf(correct)};
}
function item(prefix,level,index,topic,prompt,correct,wrong,solution,extra={}){const o=rotate([correct,...wrong],index+levels.indexOf(level));return {id:`${prefix}-${levelCode[level]}-${String(index).padStart(2,"0")}`,universidadReferencia:level==="admision"?"UNI":"GENERAL",dificultad:level,tema:topic,subarea:extra.subarea||"Aptitud académica",competencia:level==="admision"?"Integra condiciones en formato de admisión":"Aplica conceptos y verifica el procedimiento",pregunta:prompt,alternativas:o.alternativas,respuesta:o.respuesta,solucion:solution,explicacion:extra.explicacion||solution,pasosMinimos:level==="basico"?1:level==="intermedio"?2:level==="avanzado"?3:4,fuenteReferencia:extra.fuente||"Carpeta académica compartida del proyecto",alineacionUniversitaria:"Ejercicio original de UniPrep inspirado en la cobertura temática del material; no es pregunta oficial",...(extra.figura?{figura:extra.figura}:{})};}
function makeTopic(id,title,subarea,questions,source,points){const niveles={};let k=0;for(const level of levels){niveles[level]=questions.slice(k,k+distribution[level]).map((q,i)=>item(id.toUpperCase(),level,i+1,title,q.prompt,q.correct,q.wrong,q.solution,{subarea,fuente:source,figura:q.figura,explicacion:q.explicacion}));k+=distribution[level];}return {id,titulo:title,subarea,duracion:"45 min",teoria:`Cobertura reconstruida desde ${source}.`,puntos:points,fuenteTematica:source,distribucion:{...distribution},niveles};}
function addTopics(file,topics){const p=path.join(BANK,file),d=JSON.parse(fs.readFileSync(p,"utf8")),ids=new Set(topics.map(t=>t.id));if(file==="rv.json")["rv-09","rv-10","rv-11"].forEach(id=>ids.add(id));d.temas=d.temas.filter(t=>!ids.has(t.id)).concat(topics);d.version="2026.32-cobertura-drive";d.total=d.temas.length*45;d.distribucion={basico:d.temas.length*10,intermedio:d.temas.length*10,avanzado:d.temas.length*10,admision:d.temas.length*15,total:d.total};d.distribucionPorTema={...distribution};fs.writeFileSync(p,JSON.stringify(d,null,2)+"\n");}

const lexicon=[
["abstruso","difícil","claro","De comprensión difícil"],["acucioso","diligente","negligente","Que trabaja con cuidado y atención"],["adusto","severo","afable","Serio y poco tratable"],["altruista","generoso","egoísta","Que procura el bien ajeno"],["ambiguo","equívoco","inequívoco","Que admite más de una interpretación"],["apócrifo","falso","auténtico","De autoría o autenticidad dudosa"],["baladí","insignificante","trascendente","De poca importancia"],["beligerante","combativo","pacífico","Inclinado al enfrentamiento"],["cándido","ingenuo","malicioso","Que actúa sin malicia"],["cauto","prudente","temerario","Que procede con precaución"],["conciso","breve","prolijo","Que expresa mucho con pocas palabras"],["contumaz","obstinado","dócil","Persistente en un error"],["deferente","respetuoso","descortés","Que muestra consideración"],["deleznable","despreciable","admirable","Que merece rechazo por su bajeza"],["diáfano","claro","turbio","Limpio o fácil de comprender"],["dilapidar","malgastar","ahorrar","Gastar bienes de manera desordenada"],["ecuánime","imparcial","parcial","Que juzga con serenidad y justicia"],["efímero","pasajero","duradero","Que dura poco tiempo"],["elocuente","expresivo","inexpresivo","Que comunica con eficacia"],["enervar","debilitar","fortalecer","Quitar fuerza o energía"],["exiguo","escaso","abundante","Insuficiente o muy reducido"],["falaz","engañoso","veraz","Que induce al error"],["flemático","calmado","iracundo","De temperamento sereno"],["frugal","moderado","opulento","Sobrio en comida o gastos"],["huraño","insociable","sociable","Que rehúye el trato"],["ignoto","desconocido","conocido","No conocido ni descubierto"],["incólume","ileso","dañado","Que no sufrió lesión"],["inefable","indescriptible","expresable","Que no puede explicarse con palabras"],["inherente","propio","ajeno","Unido esencialmente a algo"],["lacónico","breve","verboso","Que habla con pocas palabras"],["loable","elogiable","censurable","Digno de alabanza"],["mendaz","mentiroso","sincero","Que acostumbra mentir"],["nítido","claro","borroso","Que se distingue con precisión"],["ocioso","inactivo","laborioso","Que carece de ocupación"],["parco","moderado","excesivo","Sobrio o escaso en palabras"],["perenne","permanente","temporal","Que continúa por largo tiempo"],["plausible","admisible","inaceptable","Que puede aceptarse razonablemente"],["prístino","original","alterado","Antiguo y conservado sin cambio"],["probo","honrado","corrupto","De conducta íntegra"],["reacio","renuente","dispuesto","Que se resiste a hacer algo"],["sagaz","perspicaz","torpe","Que comprende con rapidez"],["sucinto","resumido","extenso","Expresado brevemente"],["tácito","implícito","explícito","Que se entiende sin decirse"],["ubérrimo","fértil","estéril","Muy abundante y fértil"],["vehemente","intenso","apático","Que actúa con fuerza y pasión"]
];
function lexicalQuestions(kind){return lexicon.map((e,i)=>{const [word,syn,ant,def]=e;const answer=kind==="sin"?syn:kind==="ant"?ant:word;const pool=lexicon.filter((_,j)=>j!==i).map(x=>kind==="sin"?x[1]:kind==="ant"?x[2]:x[0]);const wrong=[pool[(i+7)%44],pool[(i+19)%44],pool[(i+31)%44]];return {prompt:kind==="sin"?`Señale el sinónimo más preciso de «${word}».`:kind==="ant"?`Señale el antónimo más preciso de «${word}».`:`¿Qué término corresponde a la definición «${def}»?`,correct:answer,wrong,solution:kind==="sin"?`«${word}» y «${syn}» comparten el núcleo de significado.`:kind==="ant"?`«${ant}» expresa la oposición semántica más directa de «${word}».`:`La definición corresponde a «${word}».`};});}

function clockQuestions(){const times=[];for(let h=1;h<=11&&times.length<45;h++)for(const m of [5,10,15,20,25]){if(times.length>=45)break;const raw=Math.abs(30*h-5.5*m),angle=Math.min(raw,360-raw);const format=v=>`${v.toFixed(1).replace(".0","")}°`,correct=format(angle);const candidates=[Math.abs(30*h-6*m),Math.min(180,angle+15),Math.max(0,angle-10),angle+7,Math.max(0,angle-17)].map(format);const wrong=[...new Set(candidates.filter(value=>value!==correct))];let delta=11;while(wrong.length<3){const candidate=format((angle+delta)%181);if(candidate!==correct&&!wrong.includes(candidate))wrong.push(candidate);delta+=7;}times.push({prompt:`El reloj mostrado marca las ${h}:${String(m).padStart(2,"0")}. ¿Cuál es el menor ángulo entre sus manecillas?`,correct,wrong:wrong.slice(0,3),solution:`Ángulo horario=30(${h})+0,5(${m}); ángulo minutero=6(${m}). La diferencia menor es ${correct}.`,figura:{tipo:"reloj",hora:h,minuto:m}});}return times;}

function inductionQuestions(){const out=[];for(let i=0;i<15;i++){const a=2+i,d=2+(i%5),seq=[a,a+d,a+2*d,a+3*d],ans=a+4*d;out.push({prompt:`Complete la sucesión ${seq.join(", ")}, …`,correct:ans,wrong:[ans-d,ans+d,ans+2*d],solution:`La diferencia constante es ${d}; el siguiente término es ${ans}.`});}for(let i=0;i<15;i++){const a=1+i,r=2+(i%3),seq=[a,a*r,a*r*r,a*r*r*r],ans=a*r**4;out.push({prompt:`Determine el término siguiente: ${seq.join(", ")}, …`,correct:ans,wrong:[a*r**3+r,ans-r,ans+r],solution:`Cada término se multiplica por ${r}; por tanto sigue ${ans}.`});}for(let i=0;i<15;i++){const a=1+i,seq=[a,a+3,a+8,a+15],ans=a+24;out.push({prompt:`Halle el número que continúa en ${seq.join(", ")}, …`,correct:ans,wrong:[ans-2,ans+2,ans+4],solution:`Los incrementos son 3, 5, 7 y luego 9; resulta ${ans}.`});}return out;}

function trigGraphQuestions(){const out=[];for(let i=0;i<45;i++){const type=i%3,k=Math.floor(i/3)+1,amp=k,period=1+(k%5),fn=i%2?"cos":"sen";if(type===0)out.push({prompt:`Observe la gráfica de y=${amp}${fn}(2πx/${period}). ¿Cuál es su amplitud?`,correct:amp,wrong:[amp+1,period,2*amp],solution:`En y=A·${fn}(Bx), la amplitud es |A|=${amp}.`,figura:{tipo:"trigonometrica",funcion:fn,amplitud:amp,periodoPi:period}});else if(type===1)out.push({prompt:`La función ${fn} representada tiene amplitud ${amp} y completa un ciclo cada ${period}π unidades. ¿Cuál es su periodo?`,correct:`${period}π`,wrong:[`${2*period}π`,`π/${period}`,`${amp}π`],solution:`El periodo es la longitud horizontal de un ciclo completo: ${period}π.`,figura:{tipo:"trigonometrica",funcion:fn,amplitud:amp,periodoPi:period}});else out.push({prompt:`Según la gráfica de amplitud ${amp} y periodo ${period}π, ¿entre qué valores oscila la función?`,correct:`[−${amp}, ${amp}]`,wrong:[`[0, ${amp}]`,`[−${period}, ${period}]`,`[−${2*amp}, ${2*amp}]`],solution:`Una función sinusoidal sin traslado vertical y amplitud ${amp} tiene rango [−${amp}, ${amp}].`,figura:{tipo:"trigonometrica",funcion:fn,amplitud:amp,periodoPi:period}});}return out;}

function circleQuestions(){const angles=[0,30,45,60,90,120,135,150,180,210,225,240,270,300,315];const exact={0:["0","1"],30:["1/2","√3/2"],45:["√2/2","√2/2"],60:["√3/2","1/2"],90:["1","0"],120:["√3/2","−1/2"],135:["√2/2","−√2/2"],150:["1/2","−√3/2"],180:["0","−1"],210:["−1/2","−√3/2"],225:["−√2/2","−√2/2"],240:["−√3/2","−1/2"],270:["−1","0"],300:["−√3/2","1/2"],315:["−√2/2","√2/2"]};const out=[];for(let round=0;round<3;round++)for(const ang of angles){const fn=round===0?"sen":round===1?"cos":"signo del producto sen·cos";if(round<2){const ans=exact[ang][round];out.push({prompt:`En la circunferencia trigonométrica, determine ${fn} ${ang}°.`,correct:ans,wrong:[round?exact[ang][0]:exact[ang][1],ans.startsWith("−")?ans.slice(1):`−${ans}`,"1"],solution:`Se ubica ${ang}° en su cuadrante y se toma la coordenada ${round===0?"vertical (seno)":"horizontal (coseno)"}: ${ans}.`});}else{const s=exact[ang][0],c=exact[ang][1],ans=(s.startsWith("−")!==c.startsWith("−"))?"negativo":(s==="0"||c==="0")?"cero":"positivo";out.push({prompt:`Para θ=${ang}°, ¿cuál es el signo de senθ·cosθ?`,correct:ans,wrong:["positivo","negativo","cero"].filter(x=>x!==ans).concat(["no definido"]).slice(0,3),solution:`Los signos del seno y coseno en ${ang}° determinan que el producto sea ${ans}.`});}}return out;}

const rvSource="UNMSM Preguntas de Admisión RV por temas y Razonamiento Verbal 1.pdf";
addTopics("rv.json",[
  makeTopic("rv-sin","Sinonimia directa y precisión léxica","Razonamiento verbal",lexicalQuestions("sin"),rvSource,["Sinonimia","Matiz semántico","Precisión léxica"]),
  makeTopic("rv-ant","Antonimia directa","Razonamiento verbal",lexicalQuestions("ant"),rvSource,["Oposición semántica","Categoría gramatical","Contexto"]),
  makeTopic("rv-def","Definiciones y vocabulario","Razonamiento verbal",lexicalQuestions("def"),rvSource,["Definición","Vocabulario académico","Correspondencia conceptual"])
]);
addTopics("rm.json",[
  makeTopic("rm-11","Cronometría, relojes y ángulos","Razonamiento matemático",clockQuestions(),"05 Cronometría - Relojes.pdf",["Ángulo horario","Ángulo minutero","Adelantos y atrasos"]),
  makeTopic("rm-12","Razonamiento inductivo y sucesiones","Razonamiento matemático",inductionQuestions(),"02 Inductivo - Deductivo.pdf",["Patrones","Inducción","Sucesiones combinadas"])
]);
addTopics("trigonometria.json",[
  makeTopic("trigonometria-8","Circunferencia trigonométrica y reducción angular","Matemática",circleQuestions(),"04 Circunferencia trigonométrica.pdf",["Cuadrantes","Signos","Valores notables"]),
  makeTopic("trigonometria-9","Gráficas y transformaciones trigonométricas","Matemática",trigGraphQuestions(),"08 Transformaciones y 09 Funciones trigonométricas directas.pdf",["Amplitud","Periodo","Rango y transformaciones"])
]);

const report={version:"2026.32",fuentesDrive:["05 Cronometría - Relojes.pdf","02 Inductivo - Deductivo.pdf","04 Circunferencia trigonométrica.pdf","08 Transformaciones trigonométricas.pdf","09 Funciones trigonométricas directas.pdf","UNMSM Preguntas de Admisión RV por temas.pdf"],coberturaNueva:["Sinonimia directa","Antonimia directa","Definiciones","Cronometría con reloj visual","Inductivo y sucesiones","Circunferencia trigonométrica","Gráficas trigonométricas"],preguntasNuevas:315,criterio:"Ejercicios originales con solución verificable; las fuentes se usan para cobertura y exigencia, no para copia literal."};
fs.writeFileSync(path.join(ROOT,"json","auditoria-cobertura-drive-2026.32.json"),JSON.stringify(report,null,2)+"\n");
console.log(JSON.stringify(report,null,2));
